/* flow.h — GENERATED by tools/amalgamate.sh. Do not edit; edit src/ instead. */
#ifndef FLOW_H
#define FLOW_H
/* ===================== src/flow_head.h ===================== */
/* flow — a C-based xyflow (terminal node-graph editor library). MIT.
 * Single-header; generated from src/ by tools/amalgamate.sh — DO NOT edit flow.h directly.
 * Terminal escape/raw-mode technique adapted from tuibox (Cubified, MIT). */
#include <stdint.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
/* ===================== src/flow_geom.h ===================== */
/* ===== geometry (pure, no I/O) ===== */
typedef struct { int x, y; } flow_pt;
typedef struct { int x, y, w, h; } flow_rect;
typedef enum { FLOW_TOP, FLOW_RIGHT, FLOW_BOTTOM, FLOW_LEFT } flow_pos;
typedef struct { float ox, oy, zoom; } flow_viewport;

flow_pt   flow_project(flow_viewport v, flow_pt world);
flow_pt   flow_unproject(flow_viewport v, flow_pt screen);
int       flow_rect_contains(flow_rect r, flow_pt p);
int       flow_rect_intersects(flow_rect a, flow_rect b);  /* true if a and b overlap; edge-touch counts */
flow_rect flow_rect_union(flow_rect a, flow_rect b);

#ifdef FLOW_IMPLEMENTATION
flow_pt flow_project(flow_viewport v, flow_pt world) {
  flow_pt s;
  s.x = (int)lroundf(world.x * v.zoom + v.ox);
  s.y = (int)lroundf(world.y * v.zoom + v.oy);
  return s;
}
flow_pt flow_unproject(flow_viewport v, flow_pt screen) {
  float z = (v.zoom == 0.0f) ? 1.0f : v.zoom;
  flow_pt w;
  w.x = (int)lroundf((screen.x - v.ox) / z);
  w.y = (int)lroundf((screen.y - v.oy) / z);
  return w;
}
int flow_rect_contains(flow_rect r, flow_pt p) {
  return p.x >= r.x && p.x < r.x + r.w && p.y >= r.y && p.y < r.y + r.h;
}
int flow_rect_intersects(flow_rect a, flow_rect b) {
  /* edge-touch counts as overlap (closed convention) — see header: "touching edges count" */
  return a.x <= b.x + b.w && b.x <= a.x + a.w &&
         a.y <= b.y + b.h && b.y <= a.y + a.h;
}
flow_rect flow_rect_union(flow_rect a, flow_rect b) {
  int x0 = a.x < b.x ? a.x : b.x, y0 = a.y < b.y ? a.y : b.y;
  int ax1 = a.x + a.w, ay1 = a.y + a.h, bx1 = b.x + b.w, by1 = b.y + b.h;
  int x1 = ax1 > bx1 ? ax1 : bx1, y1 = ay1 > by1 ? ay1 : by1;
  flow_rect r = { x0, y0, x1 - x0, y1 - y0 };
  return r;
}
#endif
/* ===================== src/flow_cell.h ===================== */
/* ===== cells, surface, box, utf8, damage diff ===== */
enum { FLOW_BOLD = 1u, FLOW_REVERSE = 2u, FLOW_DIM = 4u, FLOW_UNDERLINE = 8u };
#define FLOW_FG 7
#define FLOW_BG 0
typedef struct { uint32_t ch; uint8_t fg, bg, attr; } flow_cell;

typedef struct { flow_cell *cells; int w, h; } flow_cellbuf;
struct flow_surface { flow_cellbuf *cb; int ox, oy, w, h; };
typedef struct flow_surface flow_surface;

/* route output type — declared here so the edge vtable can reference it; impl in flow_route.h */
typedef struct { uint32_t ch; int x, y; } flow_route_cell;
typedef struct { flow_route_cell *cells; int count, cap; flow_pt label_anchor; } flow_route;

int  flow_utf8(uint32_t cp, char out[5]);
int  flow_utf8_decode(const char *s, uint32_t *cp);
void flow_cellbuf_clear(flow_cellbuf *cb, uint8_t fg, uint8_t bg);
void flow_cellbuf_put(flow_cellbuf *cb, int x, int y, uint32_t ch, uint8_t fg, uint8_t bg, uint8_t attr);
void flow_put(flow_surface *s, int x, int y, uint32_t ch, uint8_t fg, uint8_t bg, uint8_t attr);
void flow_text(flow_surface *s, int x, int y, const char *utf8, uint8_t fg, uint8_t bg, uint8_t attr);
void flow_box(flow_surface *s, int x, int y, int w, int h, uint8_t fg, uint8_t bg, unsigned style);
int  flow_surface_w(const flow_surface *s);
int  flow_surface_h(const flow_surface *s);
char *flow_diff_emit(const flow_cell *front, const flow_cell *back, int cols, int rows);

#ifdef FLOW_IMPLEMENTATION
int flow_utf8(uint32_t cp, char out[5]) {
  if (cp < 0x80) { out[0] = (char)cp; out[1] = 0; return 1; }
  if (cp < 0x800) { out[0] = (char)(0xC0 | (cp >> 6)); out[1] = (char)(0x80 | (cp & 0x3F)); out[2] = 0; return 2; }
  if (cp < 0x10000) { out[0] = (char)(0xE0 | (cp >> 12)); out[1] = (char)(0x80 | ((cp >> 6) & 0x3F));
    out[2] = (char)(0x80 | (cp & 0x3F)); out[3] = 0; return 3; }
  out[0] = (char)(0xF0 | (cp >> 18)); out[1] = (char)(0x80 | ((cp >> 12) & 0x3F));
  out[2] = (char)(0x80 | ((cp >> 6) & 0x3F)); out[3] = (char)(0x80 | (cp & 0x3F)); out[4] = 0; return 4;
}
int flow_utf8_decode(const char *s, uint32_t *cp) {
  const unsigned char *u = (const unsigned char*)s;
  /* Each continuation check short-circuits before the next byte is read, so a
     truncated trailing sequence stops at the NUL instead of over-reading. */
  if (u[0] < 0x80) { *cp = u[0]; return 1; }
  if ((u[0] & 0xE0) == 0xC0) {
    if ((u[1] & 0xC0) != 0x80) { *cp = u[0]; return 1; }
    *cp = ((uint32_t)(u[0]&0x1F)<<6)|(u[1]&0x3F); return 2;
  }
  if ((u[0] & 0xF0) == 0xE0) {
    if ((u[1] & 0xC0) != 0x80 || (u[2] & 0xC0) != 0x80) { *cp = u[0]; return 1; }
    *cp = ((uint32_t)(u[0]&0x0F)<<12)|((uint32_t)(u[1]&0x3F)<<6)|(u[2]&0x3F); return 3;
  }
  if ((u[0] & 0xF8) == 0xF0) {
    if ((u[1]&0xC0)!=0x80 || (u[2]&0xC0)!=0x80 || (u[3]&0xC0)!=0x80) { *cp = u[0]; return 1; }
    *cp = ((uint32_t)(u[0]&0x07)<<18)|((uint32_t)(u[1]&0x3F)<<12)|((uint32_t)(u[2]&0x3F)<<6)|(u[3]&0x3F); return 4;
  }
  *cp = u[0]; return 1;   /* invalid lead byte */
}
void flow_cellbuf_clear(flow_cellbuf *cb, uint8_t fg, uint8_t bg) {
  for (int i = 0; i < cb->w * cb->h; i++) { cb->cells[i].ch = ' '; cb->cells[i].fg = fg; cb->cells[i].bg = bg; cb->cells[i].attr = 0; }
}
void flow_cellbuf_put(flow_cellbuf *cb, int x, int y, uint32_t ch, uint8_t fg, uint8_t bg, uint8_t attr) {
  if (x < 0 || y < 0 || x >= cb->w || y >= cb->h) return;
  flow_cell *c = &cb->cells[y * cb->w + x]; c->ch = ch; c->fg = fg; c->bg = bg; c->attr = attr;
}
void flow_put(flow_surface *s, int x, int y, uint32_t ch, uint8_t fg, uint8_t bg, uint8_t attr) {
  if (x < 0 || y < 0 || x >= s->w || y >= s->h) return;            /* logical clip to node box */
  flow_cellbuf_put(s->cb, s->ox + x, s->oy + y, ch, fg, bg, attr); /* physical clip to buffer  */
}
void flow_text(flow_surface *s, int x, int y, const char *u, uint8_t fg, uint8_t bg, uint8_t attr) {
  int i = 0; while (*u) { uint32_t cp; int n = flow_utf8_decode(u, &cp); u += n; flow_put(s, x + i, y, cp, fg, bg, attr); i++; }
}
void flow_box(flow_surface *s, int x, int y, int w, int h, uint8_t fg, uint8_t bg, unsigned style) {
  uint8_t a = (style & FLOW_BOLD) ? FLOW_BOLD : 0;
  if (w < 2 || h < 2) return;
  flow_put(s, x, y, 0x250C, fg, bg, a);
  flow_put(s, x+w-1, y, 0x2510, fg, bg, a);
  flow_put(s, x, y+h-1, 0x2514, fg, bg, a);
  flow_put(s, x+w-1, y+h-1, 0x2518, fg, bg, a);
  for (int i = 1; i < w-1; i++) { flow_put(s, x+i, y, 0x2500, fg, bg, a); flow_put(s, x+i, y+h-1, 0x2500, fg, bg, a); }
  for (int j = 1; j < h-1; j++) { flow_put(s, x, y+j, 0x2502, fg, bg, a); flow_put(s, x+w-1, y+j, 0x2502, fg, bg, a); }
}
int flow_surface_w(const flow_surface *s) { return s->w; }
int flow_surface_h(const flow_surface *s) { return s->h; }

static void flow__sb(char **out, size_t *cap, size_t *len, const char *s, int n) {
  if (*len + (size_t)n + 1 > *cap) { while (*len + (size_t)n + 1 > *cap) *cap *= 2; *out = (char*)realloc(*out, *cap); }
  memcpy(*out + *len, s, n); *len += n; (*out)[*len] = 0;
}
char *flow_diff_emit(const flow_cell *front, const flow_cell *back, int cols, int rows) {
  size_t cap = 64, len = 0; char *out = (char*)malloc(cap); out[0] = 0;
  int cury = -1, curx = -1, have_style = 0; uint8_t lfg = 0, lbg = 0, lattr = 0;
  char tmp[64], u[5];
  for (int y = 0; y < rows; y++) for (int x = 0; x < cols; x++) {
    int i = y * cols + x; flow_cell b = back[i], f = front[i];
    if (b.ch == f.ch && b.fg == f.fg && b.bg == f.bg && b.attr == f.attr) continue;
    if (y != cury || x != curx) { int n = snprintf(tmp, sizeof tmp, "\x1b[%d;%dH", y+1, x+1); flow__sb(&out,&cap,&len,tmp,n); }
    if (!have_style || b.fg != lfg || b.bg != lbg || b.attr != lattr) {
      int k = 0; k += snprintf(tmp+k, sizeof tmp-k, "\x1b[0");
      if (b.attr & FLOW_BOLD) k += snprintf(tmp+k, sizeof tmp-k, ";1");
      if (b.attr & FLOW_REVERSE) k += snprintf(tmp+k, sizeof tmp-k, ";7");
      k += snprintf(tmp+k, sizeof tmp-k, ";38;5;%u;48;5;%um", b.fg, b.bg);
      flow__sb(&out,&cap,&len,tmp,k); lfg=b.fg; lbg=b.bg; lattr=b.attr; have_style=1;
    }
    uint32_t ch = b.ch ? b.ch : ' '; int n = flow_utf8(ch, u); flow__sb(&out,&cap,&len,u,n);
    curx = x + 1; cury = y;
  }
  return out;
}
#endif
/* ===================== src/flow_model.h ===================== */
/* ===== model: engine, nodes, edges, vtable types, transform, bounds, hit-test ===== */
enum { FLOW_SELECTED = 1u, FLOW_DRAGGING = 2u, FLOW_HOVERED = 4u };
typedef enum { FLOW_HANDLE_SOURCE, FLOW_HANDLE_TARGET, FLOW_HANDLE_BOTH } flow_handle_kind;
typedef struct { char id[16]; flow_handle_kind kind; flow_pos pos; int along; } flow_handle; /* id must be a NUL-terminated C-string (matched by strcmp/strncmp, like node type[]/edge handle[]) */

typedef struct { int id; char type[32]; flow_pt pos; int parent; int w, h; void *data; unsigned flags; } flow_node;
typedef struct { int id, source, target; char source_handle[16], target_handle[16];
                 char type[16]; char *label; void *data; unsigned flags; } flow_edge;

typedef struct { float zoom; unsigned flags; int lod; } flow_render_ctx;
typedef struct { const char *type;
  void (*measure)(const flow_node*, int*, int*);
  void (*render)(const flow_node*, flow_surface*, flow_render_ctx);
  const flow_handle *handles; int handle_count; } flow_node_type;
typedef struct { const char *type;
  void (*route)(flow_pt s, flow_pos sp, flow_pt t, flow_pos tp, flow_route *out); } flow_edge_type;

typedef struct flow flow_t;

/* keyboard command dispatch — a key fn runs from flow_feed when its seq matches */
typedef void (*flow_key_fn)(flow_t *f, void *user);

flow_t *flow_new(int cols, int rows);
void    flow_free(flow_t *f);
void    flow_resize(flow_t *f, int cols, int rows);
void    flow_register_node_type(flow_t *f, const flow_node_type *t);
void    flow_register_edge_type(flow_t *f, const flow_edge_type *t);
const flow_node_type *flow_node_type_for(flow_t *f, const char *type);
const flow_edge_type *flow_edge_type_for(flow_t *f, const char *type);
void    flow_measure_node(flow_t *f, flow_node *n);
int     flow_add_node(flow_t *f, const char *type, flow_pt pos, void *data);
void    flow_move_node(flow_t *f, int id, flow_pt pos);
int     flow_add_edge(flow_t *f, int src, int dst, const char *sh, const char *th);
flow_node *flow_get_node(flow_t *f, int id);
flow_edge *flow_get_edge(flow_t *f, int id);
int     flow_node_count(flow_t *f);
int     flow_edge_count(flow_t *f);
flow_node *flow_nodes(flow_t *f);
flow_edge *flow_edges(flow_t *f);
flow_pt   flow_node_abs(flow_t *f, const flow_node *n);
flow_rect flow_node_rect_abs(flow_t *f, const flow_node *n);
flow_rect flow_bounds(flow_t *f);
int       flow_hit_node(flow_t *f, flow_pt screen);
void      flow_pan(flow_t *f, int dx, int dy);
flow_pt   flow_to_screen(flow_t *f, flow_pt world_abs);
flow_pt   flow_to_world(flow_t *f, flow_pt screen);
flow_viewport flow_view_get(flow_t *f);

/* handles & connections (port-handle drag/click to create edges) */
flow_pt flow_handle_anchor(flow_t *f, const flow_node *n, const flow_handle *h); /* world-abs cell: TOP->(x+w/2,y) RIGHT->(x+w-1,y+h/2) BOTTOM->(x+w/2,y+h-1) LEFT->(x,y+h/2), +'along' offset along the side */
int flow_node_handle_count(flow_t *f, int node);                  /* declared handles for node's type */
const flow_handle *flow_node_handle_at(flow_t *f, int node, int idx); /* idx-th handle of node's type, or NULL */
int flow_hit_handle(flow_t *f, flow_pt screen, int *out_node);   /* handle index + node id at screen cell, or -1; only on hovered/selected/connecting nodes */
void flow_set_hover(flow_t *f, int node);                         /* set FLOW_HOVERED on node (clears others); -1 clears all */
int flow_hovered_node(flow_t *f);                                 /* first FLOW_HOVERED node, or -1 */
int flow_begin_connection(flow_t *f, int node, const char *handle); /* enter connecting from source handle; 0 ok, -1 if not a valid source */
int flow_update_connection(flow_t *f, flow_pt screen);           /* move free end to screen cell; returns hovered candidate target node id or -1 */
int flow_end_connection(flow_t *f, int node, const char *handle);/* complete: add edge src->node; returns new edge id or -1; clears connecting */
void flow_cancel_connection(flow_t *f);                          /* abort in-flight connection */
int flow_connecting(flow_t *f);                                  /* 1 while a connection/preview is in flight */

/* selection — a true set, expressed via the FLOW_SELECTED node flag */
typedef enum { FLOW_SELECT_PARTIAL, FLOW_SELECT_FULL } flow_select_mode;
void flow_select_node(flow_t *f, int id, int additive);  /* additive=0 clears others then sets; additive=1 sets without clearing */
void flow_toggle_node(flow_t *f, int id);   /* add to selection if unset, remove if set; never clears others */
void flow_clear_selection(flow_t *f);
int  flow_selected_node(flow_t *f);   /* first selected node id, or -1 */
int  flow_selected_edge(flow_t *f);   /* first selected edge id, or -1 */
void flow_select_edge(flow_t *f, int id, int additive);  /* set FLOW_SELECTED on the edge; !additive clears node + other edge selection first (mutual exclusivity) */
int  flow_selected_count(flow_t *f);  /* number of FLOW_SELECTED nodes */
int  flow_selected_nodes(flow_t *f, int *out, int max);  /* fill out[] with selected ids in insertion order; returns total count (may exceed max) */
int  flow_select_in_rect(flow_t *f, flow_rect world, flow_select_mode mode, int additive);  /* select nodes contained (FULL) or intersecting (PARTIAL) the world rect; !additive clears first; returns count selected */
void flow_set_marquee_mode(flow_t *f, flow_select_mode mode);  /* default mode for shift-drag marquee (defaults to FLOW_SELECT_PARTIAL) */

/* mutators (callers re-fetch node/edge pointers after these — array may move) */
void flow_remove_node(flow_t *f, int id);  /* cascades incident edges AND child nodes (recursive), frees edge labels */
void flow_remove_edge(flow_t *f, int id);  /* frees label; no-op if id absent */
void flow_reconnect_edge(flow_t *f, int edge, int endpoint_node, const char *handle, int which); /* which: 0=source,1=target; repoint that endpoint; revalidated like flow_add_edge (rejects self + duplicate (source,target,handles)); edge left unchanged on rejection */
void flow_set_edge_label(flow_t *f, int edge, const char *label); /* strdup into edge->label, freeing prior; NULL clears */

/* edge hit-test & endpoints — DEFINED in flow_render.h (need the render anchor helpers).
   flow_hit_edge: topmost edge whose routed path passes within Chebyshev tol of screen, else -1.
   flow_edge_endpoint_screen: screen cell of source(0)/target(1) endpoint, matching flow_render EXACTLY; 1 on success. */
int  flow_hit_edge(flow_t *f, flow_pt screen, int tol);
int  flow_edge_endpoint_screen(flow_t *f, const flow_edge *e, int which, flow_pt *out);

/* keyboard command dispatch: bindings (registry) + built-ins, driven from flow_feed */
void flow_bind_key(flow_t *f, const char *seq, flow_key_fn fn, void *user); /* register/override; matched before built-ins, longest seq first. Up to 32 bindings, seq <=7 bytes; over-limit binds are silently ignored. */
int  flow_dispatch_key(flow_t *f, const char *seq, int n); /* run a binding/built-in for one key seq; returns bytes consumed (>0) or 0 if unhandled */
void flow_delete_selection(flow_t *f);     /* built-in: remove selected node(s) then selected edge */
int  flow_add_node_center(flow_t *f, const char *type, void *data); /* add at world point under viewport center; returns id */
void flow_fit_view(flow_t *f, int margin); /* zoom==1: pan so flow_bounds is centred; no-op when empty */
void flow_set_statusbar(flow_t *f, int enabled); /* toggle the built-in bottom help/status line */

/* callbacks — the library/app seam (panel content stays app-side, like xyflow <Panel>) */
typedef struct {
  void (*on_overlay)(flow_t *f, flow_surface *screen, void *user);        /* draw HUD/panels last */
  void (*on_node_context)(flow_t *f, int node, flow_pt screen, void *user);/* right-click on a node */
  void (*on_node_click)(flow_t *f, int node, void *user);                  /* left-click (no drag)  */
  void (*on_pane_click)(flow_t *f, flow_pt world, void *user);             /* left-click empty space */
  void (*on_connect)(flow_t *f, int source, int target, void *user);      /* a connection was created (after flow_add_edge) */
  void *user;
} flow_callbacks;
void flow_set_callbacks(flow_t *f, flow_callbacks cb);

/* minimap widget */
typedef enum { FLOW_CORNER_TL, FLOW_CORNER_TR, FLOW_CORNER_BL, FLOW_CORNER_BR } flow_corner;
void flow_set_minimap(flow_t *f, int enabled, flow_corner corner, int w, int h);

/* background grid widget (world-aligned; off by default — pass FLOW_BG_NONE to disable) */
typedef enum { FLOW_BG_NONE, FLOW_BG_DOTS, FLOW_BG_LINES, FLOW_BG_CROSS } flow_bg_variant;
void flow_set_background(flow_t *f, flow_bg_variant variant, int gap);

#ifdef FLOW_IMPLEMENTATION
struct flow {
  flow_node *nodes; int nnodes, capnodes, nextid;
  flow_edge *edges; int nedges, capedges, nexteid;
  const flow_node_type **ntypes; int nntypes;
  const flow_edge_type **etypes; int netypes;
  flow_viewport view; int cols, rows; flow_cell *front; int running;
  int drag_node, dragging_pan; flow_pt drag_grab, last_mouse;  /* mouse interaction state */
  flow_pt drag_last_world;                                     /* multi-drag: last drag pos in world coords (per-motion delta) */
  int mouse_down, down_node, moved; flow_pt down_pos;          /* press/click tracking */
  int down_modsel;                                             /* press was a SHIFT/CTRL modifier-select on a node (suppress release replace) */
  int marquee_active, marquee_on; flow_pt marquee_anchor, marquee_cur; /* marquee: armed intent / live; screen coords */
  flow_select_mode marquee_mode;                              /* default mode for shift-drag marquee */
  int conn_active, conn_node; char conn_handle[16]; flow_pt conn_end; /* in-flight connection: source node/handle + free end (screen) */
  int reconnect_edge, reconnect_which;                        /* in-flight endpoint-reconnect drag: edge id (-1 idle) + which endpoint (0=source,1=target) */
  flow_callbacks cb;
  struct { int enabled, w, h; flow_corner corner; } minimap;
  struct { flow_bg_variant variant; int gap; } bg;
  struct { char seq[8]; flow_key_fn fn; void *user; } keys[32]; int nkeys;  /* key-binding registry */
  int statusbar;  /* built-in bottom help/status line */
};
static void *flow__grow(void *arr, int *cap, int need, size_t sz) {
  if (need <= *cap) return arr;
  int c = *cap ? *cap : 8; while (c < need) c *= 2;
  arr = realloc(arr, (size_t)c * sz); *cap = c; return arr;
}
flow_t *flow_new(int cols, int rows) {
  flow_t *f = (flow_t*)calloc(1, sizeof *f);
  f->view.zoom = 1; f->cols = cols; f->rows = rows; f->nextid = 1; f->nexteid = 1;
  f->drag_node = -1; f->marquee_mode = FLOW_SELECT_PARTIAL; f->conn_node = -1;
  f->reconnect_edge = -1;
  f->front = (flow_cell*)calloc((size_t)cols * rows, sizeof(flow_cell));
  return f;
}
void flow_free(flow_t *f) {
  if (!f) return;
  for (int i = 0; i < f->nedges; i++) free(f->edges[i].label);
  free(f->nodes); free(f->edges); free(f->ntypes); free(f->etypes); free(f->front); free(f);
}
void flow_resize(flow_t *f, int cols, int rows) {
  f->cols = cols; f->rows = rows; free(f->front);
  f->front = (flow_cell*)calloc((size_t)cols * rows, sizeof(flow_cell));
}
void flow_register_node_type(flow_t *f, const flow_node_type *t) {
  f->ntypes = (const flow_node_type**)realloc(f->ntypes, (f->nntypes + 1) * sizeof *f->ntypes);
  f->ntypes[f->nntypes++] = t;
}
void flow_register_edge_type(flow_t *f, const flow_edge_type *t) {
  f->etypes = (const flow_edge_type**)realloc(f->etypes, (f->netypes + 1) * sizeof *f->etypes);
  f->etypes[f->netypes++] = t;
}
const flow_node_type *flow_node_type_for(flow_t *f, const char *type) {
  for (int i = 0; i < f->nntypes; i++) if (strcmp(f->ntypes[i]->type, type) == 0) return f->ntypes[i];
  return NULL;
}
const flow_edge_type *flow_edge_type_for(flow_t *f, const char *type) {
  for (int i = 0; i < f->netypes; i++) if (strcmp(f->etypes[i]->type, type) == 0) return f->etypes[i];
  return NULL;
}
void flow_measure_node(flow_t *f, flow_node *n) {
  const flow_node_type *t = flow_node_type_for(f, n->type);
  if (t && t->measure) { int w = 0, h = 0; t->measure(n, &w, &h); n->w = w; n->h = h; }
  else { n->w = 4; n->h = 3; }
}
int flow_add_node(flow_t *f, const char *type, flow_pt pos, void *data) {
  f->nodes = (flow_node*)flow__grow(f->nodes, &f->capnodes, f->nnodes + 1, sizeof(flow_node));
  flow_node *n = &f->nodes[f->nnodes++]; memset(n, 0, sizeof *n);
  n->id = f->nextid++; snprintf(n->type, sizeof n->type, "%s", type ? type : "default");
  n->pos = pos; n->parent = -1; n->data = data; flow_measure_node(f, n);
  return n->id;
}
void flow_move_node(flow_t *f, int id, flow_pt pos) {
  flow_node *n = flow_get_node(f, id);
  if (n) n->pos = pos;   /* increment 1/2a: top-level nodes only, so pos == absolute */
}
int flow_add_edge(flow_t *f, int src, int dst, const char *sh, const char *th) {
  if (src == dst) return -1;
  if (!flow_get_node(f, src) || !flow_get_node(f, dst)) return -1;
  const char *shs = sh ? sh : "", *ths = th ? th : "";
  for (int i = 0; i < f->nedges; i++)                          /* dup = same (source,target,handles) */
    if (f->edges[i].source == src && f->edges[i].target == dst &&
        strcmp(f->edges[i].source_handle, shs) == 0 && strcmp(f->edges[i].target_handle, ths) == 0) return -1;
  f->edges = (flow_edge*)flow__grow(f->edges, &f->capedges, f->nedges + 1, sizeof(flow_edge));
  flow_edge *e = &f->edges[f->nedges++]; memset(e, 0, sizeof *e);
  e->id = f->nexteid++; e->source = src; e->target = dst;
  snprintf(e->source_handle, sizeof e->source_handle, "%s", sh ? sh : "");
  snprintf(e->target_handle, sizeof e->target_handle, "%s", th ? th : "");
  return e->id;
}
flow_node *flow_get_node(flow_t *f, int id) { for (int i = 0; i < f->nnodes; i++) if (f->nodes[i].id == id) return &f->nodes[i]; return NULL; }
flow_edge *flow_get_edge(flow_t *f, int id) { for (int i = 0; i < f->nedges; i++) if (f->edges[i].id == id) return &f->edges[i]; return NULL; }
int flow_node_count(flow_t *f) { return f->nnodes; }
int flow_edge_count(flow_t *f) { return f->nedges; }
flow_node *flow_nodes(flow_t *f) { return f->nodes; }
flow_edge *flow_edges(flow_t *f) { return f->edges; }
flow_pt flow_node_abs(flow_t *f, const flow_node *n) {
  flow_pt p = n->pos; int parent = n->parent, guard = 0;
  while (parent != -1 && guard++ < 1024) { flow_node *pn = flow_get_node(f, parent); if (!pn) break;
    p.x += pn->pos.x; p.y += pn->pos.y; parent = pn->parent; }
  return p;
}
flow_rect flow_node_rect_abs(flow_t *f, const flow_node *n) { flow_pt a = flow_node_abs(f, n); flow_rect r = { a.x, a.y, n->w, n->h }; return r; }
flow_rect flow_bounds(flow_t *f) {
  if (f->nnodes == 0) { flow_rect z = {0,0,0,0}; return z; }
  flow_rect b = flow_node_rect_abs(f, &f->nodes[0]);
  for (int i = 1; i < f->nnodes; i++) b = flow_rect_union(b, flow_node_rect_abs(f, &f->nodes[i]));
  return b;
}
int flow_hit_node(flow_t *f, flow_pt screen) {
  for (int i = f->nnodes - 1; i >= 0; i--) {        /* topmost first */
    flow_node *n = &f->nodes[i]; flow_rect wr = flow_node_rect_abs(f, n);
    flow_pt s = flow_to_screen(f, (flow_pt){ wr.x, wr.y });
    flow_rect sr = { s.x, s.y, wr.w, wr.h };          /* zoom==1 in increment 1: size unscaled */
    if (flow_rect_contains(sr, screen)) return n->id;
  }
  return -1;
}
void flow_pan(flow_t *f, int dx, int dy) { f->view.ox += dx; f->view.oy += dy; }
flow_pt flow_to_screen(flow_t *f, flow_pt world_abs) { return flow_project(f->view, world_abs); }
flow_pt flow_to_world(flow_t *f, flow_pt screen) { return flow_unproject(f->view, screen); }
flow_viewport flow_view_get(flow_t *f) { return f->view; }
void flow_select_node(flow_t *f, int id, int additive) {
  if (!additive) {
    for (int i = 0; i < f->nnodes; i++) f->nodes[i].flags &= ~FLOW_SELECTED;
    for (int i = 0; i < f->nedges; i++) f->edges[i].flags &= ~FLOW_SELECTED;  /* mutual exclusivity: deselect any edge */
  }
  flow_node *n = flow_get_node(f, id); if (n) n->flags |= FLOW_SELECTED;
}
void flow_toggle_node(flow_t *f, int id) {
  flow_node *n = flow_get_node(f, id); if (n) n->flags ^= FLOW_SELECTED;  /* never clears others */
}
void flow_clear_selection(flow_t *f) {
  for (int i = 0; i < f->nnodes; i++) f->nodes[i].flags &= ~FLOW_SELECTED;
  for (int i = 0; i < f->nedges; i++) f->edges[i].flags &= ~FLOW_SELECTED;  /* edges too */
}
int flow_selected_node(flow_t *f) { for (int i = 0; i < f->nnodes; i++) if (f->nodes[i].flags & FLOW_SELECTED) return f->nodes[i].id; return -1; }
int flow_selected_count(flow_t *f) { int c = 0; for (int i = 0; i < f->nnodes; i++) if (f->nodes[i].flags & FLOW_SELECTED) c++; return c; }
int flow_selected_nodes(flow_t *f, int *out, int max) {
  int c = 0;                                            /* insertion order; total may exceed max */
  for (int i = 0; i < f->nnodes; i++) if (f->nodes[i].flags & FLOW_SELECTED) { if (c < max && out) out[c] = f->nodes[i].id; c++; }
  return c;
}
int flow_select_in_rect(flow_t *f, flow_rect world, flow_select_mode mode, int additive) {
  if (!additive) flow_clear_selection(f);
  int c = 0;
  for (int i = 0; i < f->nnodes; i++) {
    flow_node *n = &f->nodes[i];
    flow_rect nr = flow_node_rect_abs(f, n);            /* world rect; zoom==1 carry-over */
    int hit;
    if (mode == FLOW_SELECT_FULL) {                     /* node fully inside marquee */
      hit = nr.x >= world.x && nr.y >= world.y &&
            nr.x + nr.w <= world.x + world.w && nr.y + nr.h <= world.y + world.h;
    } else {                                            /* PARTIAL: any overlap */
      hit = flow_rect_intersects(world, nr);
    }
    if (hit) { n->flags |= FLOW_SELECTED; c++; }
  }
  return c;
}
void flow_set_marquee_mode(flow_t *f, flow_select_mode mode) { f->marquee_mode = mode; }
void flow_set_callbacks(flow_t *f, flow_callbacks cb) { f->cb = cb; }
void flow_set_minimap(flow_t *f, int enabled, flow_corner corner, int w, int h) {
  f->minimap.enabled = enabled; f->minimap.corner = corner; f->minimap.w = w; f->minimap.h = h;
}
void flow_set_background(flow_t *f, flow_bg_variant variant, int gap) {
  f->bg.variant = variant; f->bg.gap = gap < 1 ? 1 : gap;  /* gap>=1 clamp: no modulo-by-zero */
}
int flow_selected_edge(flow_t *f) {
  for (int i = 0; i < f->nedges; i++) if (f->edges[i].flags & FLOW_SELECTED) return f->edges[i].id;
  return -1;
}
void flow_select_edge(flow_t *f, int id, int additive) {
  if (!additive) flow_clear_selection(f);  /* clears node AND other edge selection (mutual exclusivity) */
  flow_edge *e = flow_get_edge(f, id); if (e) e->flags |= FLOW_SELECTED;
}
void flow_reconnect_edge(flow_t *f, int edge, int endpoint_node, const char *handle, int which) {
  flow_edge *e = flow_get_edge(f, edge);
  if (!e || !flow_get_node(f, endpoint_node)) return;
  /* compute the prospective endpoints/handles, validate, THEN commit (no rollback) */
  int nsrc = e->source, ntgt = e->target;
  const char *nsh = e->source_handle, *nth = e->target_handle;
  const char *hs = handle ? handle : "";
  if (which == 0) { nsrc = endpoint_node; nsh = hs; } else { ntgt = endpoint_node; nth = hs; }
  if (nsrc == ntgt) return;                                    /* reject self-edge */
  for (int i = 0; i < f->nedges; i++) {                        /* reject duplicate (skip this edge) */
    if (f->edges[i].id == edge) continue;
    if (f->edges[i].source == nsrc && f->edges[i].target == ntgt &&
        strcmp(f->edges[i].source_handle, nsh) == 0 &&
        strcmp(f->edges[i].target_handle, nth) == 0) return;
  }
  e->source = nsrc; e->target = ntgt;   /* scalar self-assign on the unchanged side is harmless */
  /* write ONLY the changed endpoint's handle, from the caller arg `hs` (never aliases
     e's buffers). Rewriting the unchanged side from e->*_handle would be a self-overlapping
     snprintf (UB per C11 7.21.6.5), so leave it untouched. */
  if (which == 0) snprintf(e->source_handle, sizeof e->source_handle, "%s", hs);
  else            snprintf(e->target_handle, sizeof e->target_handle, "%s", hs);
}
void flow_set_edge_label(flow_t *f, int edge, const char *label) {
  flow_edge *e = flow_get_edge(f, edge); if (!e) return;
  free(e->label); e->label = NULL;
  if (label) {                                                 /* malloc+memcpy (avoid strdup decl issues under -std=c11) */
    size_t n = strlen(label) + 1;
    e->label = (char*)malloc(n);
    if (e->label) memcpy(e->label, label, n);
  }
}
void flow_remove_edge(flow_t *f, int id) {
  for (int i = 0; i < f->nedges; i++) {
    if (f->edges[i].id != id) continue;
    free(f->edges[i].label);                                  /* free-then-shift: no leak, no dbl-free */
    memmove(&f->edges[i], &f->edges[i+1], (size_t)(f->nedges - i - 1) * sizeof(flow_edge));
    f->nedges--;                                              /* preserve insertion order */
    return;
  }
  /* absent id: no-op */
}
void flow_remove_node(flow_t *f, int id) {
  /* never hold a node/edge pointer across mutation: re-find by id each step (array moves). */
  for (;;) {                                                  /* recursively remove child nodes first */
    int childid = -1;
    for (int i = 0; i < f->nnodes; i++) if (f->nodes[i].parent == id) { childid = f->nodes[i].id; break; }
    if (childid == -1) break;
    flow_remove_node(f, childid);                             /* shrinks array; cycle-safe, terminates */
  }
  for (int i = 0; i < f->nedges; ) {                          /* remove incident edges, freeing labels */
    if (f->edges[i].source == id || f->edges[i].target == id) {
      free(f->edges[i].label);
      memmove(&f->edges[i], &f->edges[i+1], (size_t)(f->nedges - i - 1) * sizeof(flow_edge));
      f->nedges--;                                            /* do NOT i++ on the removal branch */
    } else i++;
  }
  for (int i = 0; i < f->nnodes; i++) {                       /* finally remove the node slot */
    if (f->nodes[i].id != id) continue;
    memmove(&f->nodes[i], &f->nodes[i+1], (size_t)(f->nnodes - i - 1) * sizeof(flow_node));
    f->nnodes--;
    return;
  }
}
void flow_delete_selection(flow_t *f) {
  /* remove all selected nodes (each cascades children + incident edges); re-query
     after each removal so any count works and cascade-removed selections are skipped */
  for (;;) { int id = flow_selected_node(f); if (id < 0) break; flow_remove_node(f, id); }
  for (;;) { int e  = flow_selected_edge(f); if (e  < 0) break; flow_remove_edge(f, e);  }
}
int flow_add_node_center(flow_t *f, const char *type, void *data) {
  flow_pt c = flow_to_world(f, (flow_pt){ f->cols / 2, f->rows / 2 });
  int id = flow_add_node(f, type, c, data);
  flow_node *n = flow_get_node(f, id);                        /* re-fetch for measured w,h */
  if (n) flow_move_node(f, id, (flow_pt){ c.x - n->w / 2, c.y - n->h / 2 });
  return id;
}
void flow_fit_view(flow_t *f, int margin) {
  /* zoom==1 ONLY (honest carry-over, like flow_hit_node): pure integer pan that
     centres flow_bounds. A future zoom package SUPERSEDES this exact function to
     also choose a zoom level — keep it one editable definition. `margin` is the
     unused-but-reserved usable-area inset; centring already gives equal margins. */
  (void)margin;
  if (f->nnodes == 0) return;                                 /* empty: no-op */
  flow_rect b = flow_bounds(f);
  f->view.zoom = 1;
  f->view.ox = (float)(f->cols / 2 - (b.x + b.w / 2));
  f->view.oy = (float)(f->rows / 2 - (b.y + b.h / 2));
}
void flow_set_statusbar(flow_t *f, int enabled) { f->statusbar = enabled ? 1 : 0; }
void flow_bind_key(flow_t *f, const char *seq, flow_key_fn fn, void *user) {
  if (!seq || !*seq) return;
  size_t len = strlen(seq); if (len >= sizeof f->keys[0].seq) return;  /* seq too long for slot */
  for (int i = 0; i < f->nkeys; i++)                          /* override existing binding for this seq */
    if (strcmp(f->keys[i].seq, seq) == 0) { f->keys[i].fn = fn; f->keys[i].user = user; return; }
  if (f->nkeys >= (int)(sizeof f->keys / sizeof f->keys[0])) return;   /* registry full */
  snprintf(f->keys[f->nkeys].seq, sizeof f->keys[0].seq, "%s", seq);
  f->keys[f->nkeys].fn = fn; f->keys[f->nkeys].user = user; f->nkeys++;
}
int flow_dispatch_key(flow_t *f, const char *seq, int n) {
  if (n <= 0) return 0;
  /* (1) registry: longest registered seq that fully fits in n and byte-matches. */
  int best = -1; size_t bestlen = 0;
  for (int i = 0; i < f->nkeys; i++) {
    size_t L = strlen(f->keys[i].seq);
    if (L == 0 || L > (size_t)n) continue;                    /* only claim if the ENTIRE seq fits */
    if (memcmp(f->keys[i].seq, seq, L) != 0) continue;
    if (L > bestlen) { bestlen = L; best = i; }
  }
  if (best >= 0) { if (f->keys[best].fn) f->keys[best].fn(f, f->keys[best].user); return (int)bestlen; }
  /* (2) built-ins, longest-first. Only claim if the entire seq fits in n. */
  if (n >= 4 && memcmp(seq, "\x1b[3~", 4) == 0) { flow_delete_selection(f); return 4; }  /* Delete */
  if (seq[0] == 'x') { flow_delete_selection(f); return 1; }
  if (seq[0] == 'n') { flow_add_node_center(f, "default", (void*)"node"); return 1; }    /* static label */
  if (seq[0] == 'f') { flow_fit_view(f, 2); return 1; }
  if (seq[0] == '?') { flow_set_statusbar(f, !f->statusbar); return 1; }
  /* (3) unhandled: q, bare arrows, anything else */
  return 0;
}
/* ----- handles & connections ----- */
flow_pt flow_handle_anchor(flow_t *f, const flow_node *n, const flow_handle *h) {
  flow_rect r = flow_node_rect_abs(f, n);            /* world-abs; zoom==1 carry-over (like flow_hit_node) */
  flow_pt p; int along = h ? h->along : 0;
  switch (h ? h->pos : FLOW_RIGHT) {
    case FLOW_TOP:    p.x = r.x + r.w / 2 + along; p.y = r.y;             break;
    case FLOW_BOTTOM: p.x = r.x + r.w / 2 + along; p.y = r.y + r.h - 1;   break;
    case FLOW_LEFT:   p.x = r.x;                   p.y = r.y + r.h / 2 + along; break;
    default:          p.x = r.x + r.w - 1;         p.y = r.y + r.h / 2 + along; break;  /* RIGHT */
  }
  return p;
}
int flow_node_handle_count(flow_t *f, int node) {
  flow_node *n = flow_get_node(f, node); if (!n) return 0;
  const flow_node_type *t = flow_node_type_for(f, n->type);
  return t ? t->handle_count : 0;
}
const flow_handle *flow_node_handle_at(flow_t *f, int node, int idx) {
  flow_node *n = flow_get_node(f, node); if (!n) return NULL;
  const flow_node_type *t = flow_node_type_for(f, n->type);
  if (!t || !t->handles || idx < 0 || idx >= t->handle_count) return NULL;
  return &t->handles[idx];
}
/* shared handle projection + visibility gate — flow_hit_handle and the render
   marker pass MUST agree (handles render exactly where they're hittable). The zoom
   package edits flow_handle_anchor / these two helpers in ONE place. */
static flow_pt flow__handle_screen(flow_t *f, const flow_node *n, const flow_handle *h) {
  return flow_to_screen(f, flow_handle_anchor(f, n, h));
}
static int flow__node_handles_visible(flow_t *f, const flow_node *n) {
  return (n->flags & (FLOW_HOVERED | FLOW_SELECTED)) || n->id == f->conn_node;
}
int flow_hit_handle(flow_t *f, flow_pt screen, int *out_node) {
  /* topmost first; only handles on hovered/selected/connecting nodes are hittable */
  for (int i = f->nnodes - 1; i >= 0; i--) {
    flow_node *n = &f->nodes[i];
    if (!flow__node_handles_visible(f, n)) continue;
    int hc = flow_node_handle_count(f, n->id);
    for (int j = 0; j < hc; j++) {
      const flow_handle *h = flow_node_handle_at(f, n->id, j);
      flow_pt s = flow__handle_screen(f, n, h);
      if (s.x == screen.x && s.y == screen.y) { if (out_node) *out_node = n->id; return j; }
    }
  }
  if (out_node) *out_node = -1;
  return -1;
}
void flow_set_hover(flow_t *f, int node) {
  for (int i = 0; i < f->nnodes; i++) f->nodes[i].flags &= ~FLOW_HOVERED;
  flow_node *n = flow_get_node(f, node); if (n) n->flags |= FLOW_HOVERED;
}
int flow_hovered_node(flow_t *f) {
  for (int i = 0; i < f->nnodes; i++) if (f->nodes[i].flags & FLOW_HOVERED) return f->nodes[i].id;
  return -1;
}
/* find a node's handle by id; returns it or NULL */
static const flow_handle *flow__handle_named(flow_t *f, int node, const char *id) {
  if (!id) return NULL;
  int hc = flow_node_handle_count(f, node);
  for (int j = 0; j < hc; j++) { const flow_handle *h = flow_node_handle_at(f, node, j);
    if (h && strncmp(h->id, id, sizeof h->id) == 0) return h; }
  return NULL;
}
int flow_begin_connection(flow_t *f, int node, const char *handle) {
  const flow_handle *h = flow__handle_named(f, node, handle);
  if (!h || (h->kind != FLOW_HANDLE_SOURCE && h->kind != FLOW_HANDLE_BOTH)) return -1;  /* must be a source */
  f->conn_active = 1; f->conn_node = node;
  snprintf(f->conn_handle, sizeof f->conn_handle, "%s", handle ? handle : "");
  flow_node *n = flow_get_node(f, node);
  if (n) f->conn_end = flow_to_screen(f, flow_handle_anchor(f, n, h));   /* start the free end at the source */
  return 0;
}
int flow_update_connection(flow_t *f, flow_pt screen) {
  if (!f->conn_active) return -1;
  f->conn_end = screen;
  int tn = -1; (void)flow_hit_handle(f, screen, &tn);   /* prefer a handle under the cursor */
  if (tn == -1) tn = flow_hit_node(f, screen);          /* else any node body */
  if (tn != -1 && tn != f->conn_node) flow_set_hover(f, tn);  /* reveal candidate's handles */
  return (tn != f->conn_node) ? tn : -1;
}
int flow_end_connection(flow_t *f, int node, const char *handle) {
  if (!f->conn_active) return -1;
  int src = f->conn_node; char sh[16]; snprintf(sh, sizeof sh, "%s", f->conn_handle);
  /* clear connecting state up-front so a rejected add never leaves us stuck */
  f->conn_active = 0; f->conn_node = -1; f->conn_handle[0] = 0;
  /* target handle: explicit name, else first TARGET/BOTH handle on the node */
  const char *th = handle;
  if (!th && node != -1) {
    int hc = flow_node_handle_count(f, node);
    for (int j = 0; j < hc; j++) { const flow_handle *h = flow_node_handle_at(f, node, j);
      if (h && (h->kind == FLOW_HANDLE_TARGET || h->kind == FLOW_HANDLE_BOTH)) { th = h->id; break; } }
  }
  int eid = flow_add_edge(f, src, node, sh, th);
  if (eid != -1 && f->cb.on_connect) f->cb.on_connect(f, src, node, f->cb.user);
  return eid;
}
void flow_cancel_connection(flow_t *f) {
  f->conn_active = 0; f->conn_node = -1; f->conn_handle[0] = 0;
}
int flow_connecting(flow_t *f) { return f->conn_active ? 1 : 0; }
#endif
/* ===================== src/flow_route.h ===================== */
/* ===== edge routing: orthogonal step router via path-connectivity glyphs ===== */
void flow_route_push(flow_route *r, int x, int y, uint32_t ch);
void flow_route_orthogonal(flow_pt s, flow_pos sp, flow_pt t, flow_pos tp, flow_route *out);
extern const flow_edge_type flow_default_edge_type;

#ifdef FLOW_IMPLEMENTATION
const flow_edge_type flow_default_edge_type = { "default", flow_route_orthogonal };

void flow_route_push(flow_route *r, int x, int y, uint32_t ch) {
  if (r->count >= r->cap) { r->cap = r->cap ? r->cap * 2 : 16; r->cells = (flow_route_cell*)realloc(r->cells, r->cap * sizeof *r->cells); }
  r->cells[r->count].x = x; r->cells[r->count].y = y; r->cells[r->count].ch = ch; r->count++;
}
static void flow__addpt(flow_pt **a, int *n, int *cap, int x, int y) {
  if (*n > 0 && (*a)[*n-1].x == x && (*a)[*n-1].y == y) return;
  if (*n >= *cap) { *cap = *cap ? *cap * 2 : 32; *a = (flow_pt*)realloc(*a, *cap * sizeof(flow_pt)); }
  (*a)[*n].x = x; (*a)[*n].y = y; (*n)++;
}
/* direction bit from delta (neighbor relative to cell): N=1 S=2 E=4 W=8 */
static unsigned flow__dir(int dx, int dy) { unsigned m = 0; if (dy < 0) m|=1; if (dy > 0) m|=2; if (dx > 0) m|=4; if (dx < 0) m|=8; return m; }
static uint32_t flow__glyph(unsigned m) {
  switch (m) {
    case 4: case 8: case 12: return 0x2500;   /* - (E,W,EW) */
    case 1: case 2: case 3:  return 0x2502;   /* | (N,S,NS) */
    case 6:  return 0x250C;  /* E|S */
    case 10: return 0x2510;  /* W|S */
    case 5:  return 0x2514;  /* E|N */
    case 9:  return 0x2518;  /* W|N */
    default: return 0x2500;
  }
}
void flow_route_orthogonal(flow_pt s, flow_pos sp, flow_pt t, flow_pos tp, flow_route *out) {
  (void)sp; (void)tp;
  flow_pt *p = NULL; int n = 0, cap = 0;
  int dx = t.x - s.x, dy = t.y - s.y, adx = dx<0?-dx:dx, ady = dy<0?-dy:dy;
  int sx = dx >= 0 ? 1 : -1, sy = dy >= 0 ? 1 : -1;
  if (adx >= ady) {                 /* H-V-H, bend at mid column */
    int mx = (s.x + t.x) / 2;
    for (int x = s.x; ; x += sx) { flow__addpt(&p,&n,&cap,x,s.y); if (x == mx) break; }
    for (int y = s.y; ; y += sy) { flow__addpt(&p,&n,&cap,mx,y); if (y == t.y) break; }
    for (int x = mx; ; x += sx) { flow__addpt(&p,&n,&cap,x,t.y); if (x == t.x) break; }
  } else {                          /* V-H-V, bend at mid row */
    int my = (s.y + t.y) / 2;
    for (int y = s.y; ; y += sy) { flow__addpt(&p,&n,&cap,s.x,y); if (y == my) break; }
    for (int x = s.x; ; x += sx) { flow__addpt(&p,&n,&cap,x,my); if (x == t.x) break; }
    for (int y = my; ; y += sy) { flow__addpt(&p,&n,&cap,t.x,y); if (y == t.y) break; }
  }
  for (int i = 0; i < n; i++) {
    unsigned m = 0;
    if (i > 0)     m |= flow__dir(p[i-1].x - p[i].x, p[i-1].y - p[i].y);
    if (i < n - 1) m |= flow__dir(p[i+1].x - p[i].x, p[i+1].y - p[i].y);
    flow_route_push(out, p[i].x, p[i].y, flow__glyph(m));
  }
  if (n > 0) {                      /* arrowhead at the target end, pointing along the approach */
    int ax, ay;
    if (n >= 2) { ax = p[n-1].x - p[n-2].x; ay = p[n-1].y - p[n-2].y; }
    else        { ax = t.x - s.x;           ay = t.y - s.y; }
    uint32_t arrow = ax > 0 ? 0x25B6 : ax < 0 ? 0x25C0 : ay > 0 ? 0x25BC : 0x25B2;
    out->cells[out->count - 1].ch = arrow;
    out->label_anchor = p[n/2];
  }
  free(p);
}
#endif
/* ===================== src/flow_types.h ===================== */
/* ===== default node type (data = C-string label) + register-defaults ===== */
extern const flow_node_type flow_default_node_type;
extern const flow_handle flow_default_handles[2];  /* LEFT target 'in', RIGHT source 'out' */
void flow_register_defaults(flow_t *f);

#ifdef FLOW_IMPLEMENTATION
static void flow__default_measure(const flow_node *n, int *w, int *h) {
  const char *label = n->data ? (const char*)n->data : "";
  int len = (int)strlen(label); if (len < 1) len = 1;
  *w = len + 4; *h = 3;
}
static void flow__default_render(const flow_node *n, flow_surface *s, flow_render_ctx ctx) {
  const char *label = n->data ? (const char*)n->data : "";
  unsigned bold = (ctx.flags & FLOW_SELECTED) ? FLOW_BOLD : 0;
  flow_box(s, 0, 0, flow_surface_w(s), flow_surface_h(s), FLOW_FG, FLOW_BG, bold);
  flow_text(s, 2, 1, label, FLOW_FG, FLOW_BG, bold);
}
const flow_handle flow_default_handles[2] = {
  { "in",  FLOW_HANDLE_TARGET, FLOW_LEFT,  0 },   /* input on left border  */
  { "out", FLOW_HANDLE_SOURCE, FLOW_RIGHT, 0 },   /* output on right border */
};
const flow_node_type flow_default_node_type = { "default", flow__default_measure, flow__default_render, flow_default_handles, 2 };
void flow_register_defaults(flow_t *f) {
  flow_register_node_type(f, &flow_default_node_type);
  flow_register_edge_type(f, &flow_default_edge_type);
}
#endif
/* ===================== src/flow_render.h ===================== */
/* ===== compose: render edges + nodes into a cell buffer ===== */
void flow_render(flow_t *f, flow_cell *out, int cols, int rows);

#ifdef FLOW_IMPLEMENTATION
/* Grid "light" comes from a dim 256-color fg, NOT FLOW_DIM: flow_diff_emit
   serializes only BOLD/REVERSE attrs but always the ;38;5;<fg> color path, so a
   DIM-attr grid would look full-intensity on a real terminal. 8 = bright black. */
#define FLOW_BG_GRID_FG 8
static void flow__background(flow_t *f, flow_cellbuf *cb) {
  int gap = f->bg.gap;  /* setter guarantees gap >= 1 when variant != NONE */
  for (int sy = 0; sy < cb->h; sy++) for (int sx = 0; sx < cb->w; sx++) {
    flow_pt w = flow_to_world(f, (flow_pt){ sx, sy });  /* world-align under pan */
    int onx = (w.x % gap) == 0, ony = (w.y % gap) == 0; /* ==0 is sign-safe in C */
    uint32_t ch = 0;
    switch (f->bg.variant) {
      case FLOW_BG_DOTS:  if (onx && ony) ch = 0x00B7; break;            /* · */
      case FLOW_BG_CROSS: if (onx && ony) ch = 0x002B; break;            /* + */
      case FLOW_BG_LINES:
        if (onx && ony) ch = 0x253C;       /* ┼ intersection wins */
        else if (onx)   ch = 0x2502;       /* │ vertical          */
        else if (ony)   ch = 0x2500;       /* ─ horizontal        */
        break;
      default: break;
    }
    if (ch) flow_cellbuf_put(cb, sx, sy, ch, FLOW_BG_GRID_FG, FLOW_BG, 0);
  }
}
static void flow__minimap(flow_t *f, flow_cellbuf *cb) {
  int bw = f->minimap.w, bh = f->minimap.h;
  if (bw < 4 || bh < 4) return;
  int ox, oy;
  switch (f->minimap.corner) {
    case FLOW_CORNER_TL: ox = 0;          oy = 0;          break;
    case FLOW_CORNER_TR: ox = cb->w - bw; oy = 0;          break;
    case FLOW_CORNER_BL: ox = 0;          oy = cb->h - bh; break;
    default:             ox = cb->w - bw; oy = cb->h - bh; break;  /* BR */
  }
  flow_surface s = { cb, ox, oy, bw, bh };
  flow_box(&s, 0, 0, bw, bh, FLOW_FG, FLOW_BG, 0);
  /* opaque panel: blank the interior so the background grid / edges / nodes
     underneath don't bleed through (flow_box strokes the border only) */
  for (int yy = 1; yy < bh - 1; yy++)
    for (int xx = 1; xx < bw - 1; xx++)
      flow_put(&s, xx, yy, ' ', FLOW_FG, FLOW_BG, 0);
  int iw = bw - 2, ih = bh - 2;
  /* world window encompasses all nodes and the current screen rect */
  flow_pt w0 = flow_to_world(f, (flow_pt){0, 0});
  flow_rect vp = { w0.x, w0.y, cb->w, cb->h };          /* zoom==1 */
  flow_rect W = f->nnodes ? flow_rect_union(flow_bounds(f), vp) : vp;
  if (W.w < 1) W.w = 1; if (W.h < 1) W.h = 1;
  /* viewport rectangle first, node dots on top */
  int vx  = (vp.x - W.x) * iw / W.w,             vy  = (vp.y - W.y) * ih / W.h;
  int vx2 = (vp.x + vp.w - 1 - W.x) * iw / W.w,  vy2 = (vp.y + vp.h - 1 - W.y) * ih / W.h;
  if (vx < 0) vx = 0; if (vy < 0) vy = 0;
  if (vx2 > iw - 1) vx2 = iw - 1; if (vy2 > ih - 1) vy2 = ih - 1;
  for (int x = vx; x <= vx2; x++) { flow_put(&s, 1+x, 1+vy, 0x2500, FLOW_FG, FLOW_BG, 0); flow_put(&s, 1+x, 1+vy2, 0x2500, FLOW_FG, FLOW_BG, 0); }
  for (int y = vy; y <= vy2; y++) { flow_put(&s, 1+vx, 1+y, 0x2502, FLOW_FG, FLOW_BG, 0); flow_put(&s, 1+vx2, 1+y, 0x2502, FLOW_FG, FLOW_BG, 0); }
  for (int i = 0; i < f->nnodes; i++) {
    flow_node *n = &f->nodes[i]; flow_pt a = flow_node_abs(f, n);
    int cx = a.x + n->w / 2, cy = a.y + n->h / 2;
    int mx = (cx - W.x) * iw / W.w, my = (cy - W.y) * ih / W.h;
    if (mx < 0) mx = 0; if (mx > iw - 1) mx = iw - 1;
    if (my < 0) my = 0; if (my > ih - 1) my = ih - 1;
    int sel = n->flags & FLOW_SELECTED;
    flow_put(&s, 1+mx, 1+my, sel ? 0x25C9 : 0x2022, FLOW_FG, FLOW_BG, sel ? FLOW_BOLD : 0);  /* ◉ / • */
  }
}
/* nudge a (world) anchor one cell OUTSIDE the node along the handle's facing */
static flow_pt flow__anchor_outward(flow_pt a, flow_pos pos) {
  switch (pos) {
    case FLOW_TOP:    a.y -= 1; break;
    case FLOW_BOTTOM: a.y += 1; break;
    case FLOW_LEFT:   a.x -= 1; break;
    default:          a.x += 1; break;  /* RIGHT */
  }
  return a;
}
/* resolve an edge endpoint's handle: named id -> nearest by source/target kind ->
   first handle (so flow_handle_anchor gives a side); NULL only if the type has none. */
static const flow_handle *flow__edge_handle(flow_t *f, flow_node *n, const char *id, int want_source) {
  int hc = flow_node_handle_count(f, n->id);
  if (hc <= 0) return NULL;
  if (id && id[0]) for (int j = 0; j < hc; j++) {            /* named match wins */
    const flow_handle *h = flow_node_handle_at(f, n->id, j);
    if (h && strncmp(h->id, id, sizeof h->id) == 0) return h;
  }
  flow_handle_kind kind = want_source ? FLOW_HANDLE_SOURCE : FLOW_HANDLE_TARGET;
  for (int j = 0; j < hc; j++) {                             /* first matching kind */
    const flow_handle *h = flow_node_handle_at(f, n->id, j);
    if (h && (h->kind == kind || h->kind == FLOW_HANDLE_BOTH)) return h;
  }
  return flow_node_handle_at(f, n->id, 0);                   /* fall back to first */
}
/* Screen endpoints + facings for an edge, matching EXACTLY what flow_render draws:
   declared-handle anchor -> outward nudge -> flow_to_screen. The render edge loop,
   flow_hit_edge and flow_edge_endpoint_screen all go through this so hit-test and
   render can never drift (the zoom package makes this helper zoom-aware in ONE place).
   Returns 0 if either node is missing. */
static int flow__edge_screen_ends(flow_t *f, flow_edge *e, flow_pt *ss, flow_pos *sp, flow_pt *ts, flow_pos *tp) {
  flow_node *sn = flow_get_node(f, e->source), *tn = flow_get_node(f, e->target);
  if (!sn || !tn) return 0;
  const flow_handle *sh = flow__edge_handle(f, sn, e->source_handle, 1);
  const flow_handle *th = flow__edge_handle(f, tn, e->target_handle, 0);
  flow_pos lsp = sh ? sh->pos : FLOW_RIGHT, ltp = th ? th->pos : FLOW_LEFT;
  flow_pt sa = flow__anchor_outward(flow_handle_anchor(f, sn, sh), lsp);
  flow_pt ta = flow__anchor_outward(flow_handle_anchor(f, tn, th), ltp);
  if (ss) *ss = flow_to_screen(f, sa);
  if (ts) *ts = flow_to_screen(f, ta);
  if (sp) *sp = lsp;
  if (tp) *tp = ltp;
  return 1;
}
int flow_edge_endpoint_screen(flow_t *f, const flow_edge *e, int which, flow_pt *out) {
  flow_pt ss, ts;
  if (!flow__edge_screen_ends(f, (flow_edge*)e, &ss, NULL, &ts, NULL)) return 0;  /* cast: helper takes non-const */
  if (out) *out = which == 0 ? ss : ts;
  return 1;
}
int flow_hit_edge(flow_t *f, flow_pt screen, int tol) {
  for (int i = flow_edge_count(f) - 1; i >= 0; i--) {         /* topmost first (reverse, like flow_hit_node) */
    flow_edge *e = &flow_edges(f)[i];
    flow_pt ss, ts; flow_pos sp, tp;
    if (!flow__edge_screen_ends(f, e, &ss, &sp, &ts, &tp)) continue;
    const flow_edge_type *et = flow_edge_type_for(f, e->type[0] ? e->type : "default");
    if (!et) et = &flow_default_edge_type;
    flow_route rt = {0};
    et->route(ss, sp, ts, tp, &rt);
    int hit = 0;
    for (int c = 0; c < rt.count; c++) {
      int dx = rt.cells[c].x - screen.x, dy = rt.cells[c].y - screen.y;
      if (dx < 0) dx = -dx; if (dy < 0) dy = -dy;
      if ((dx > dy ? dx : dy) <= tol) { hit = 1; break; }     /* Chebyshev distance */
    }
    free(rt.cells);
    if (hit) return e->id;
  }
  return -1;
}
void flow_render(flow_t *f, flow_cell *out, int cols, int rows) {
  flow_cellbuf cb = { out, cols, rows };
  flow_cellbuf_clear(&cb, FLOW_FG, FLOW_BG);

  /* background grid first (under edges/nodes, so it scrolls with pan) */
  if (f->bg.variant != FLOW_BG_NONE) flow__background(f, &cb);

  /* edges first (drawn under nodes). Endpoints/facings via the shared helper so the
     hit-test (flow_hit_edge) and this draw can never drift apart. */
  for (int i = 0; i < flow_edge_count(f); i++) {
    flow_edge *e = &flow_edges(f)[i];
    flow_pt ss, ts; flow_pos sp, tp;
    if (!flow__edge_screen_ends(f, e, &ss, &sp, &ts, &tp)) continue;
    const flow_edge_type *et = flow_edge_type_for(f, e->type[0] ? e->type : "default");
    if (!et) et = &flow_default_edge_type;
    flow_route rt = {0};
    et->route(ss, sp, ts, tp, &rt);
    uint8_t attr = (e->flags & FLOW_SELECTED) ? FLOW_BOLD : 0;  /* selected edge: bold path */
    for (int c = 0; c < rt.count; c++)
      flow_cellbuf_put(&cb, rt.cells[c].x, rt.cells[c].y, rt.cells[c].ch, FLOW_FG, FLOW_BG, attr);
    if (e->label) {                                            /* label on top of the path at the router anchor (screen coords), clipped */
      const char *u = e->label; int gx = rt.label_anchor.x;
      while (*u) { uint32_t cp; int n = flow_utf8_decode(u, &cp); u += n;
        flow_cellbuf_put(&cb, gx++, rt.label_anchor.y, cp, FLOW_FG, FLOW_BG, attr); }
    }
    free(rt.cells);
  }

  /* nodes on top — TWO passes over the same array so selected nodes draw LAST
     (on top), with insertion order preserved within each pass. pass 0: unselected,
     pass 1: selected. */
  for (int pass = 0; pass < 2; pass++) {
    for (int i = 0; i < flow_node_count(f); i++) {
      flow_node *n = &flow_nodes(f)[i];
      int sel = (n->flags & FLOW_SELECTED) ? 1 : 0;
      if (sel != pass) continue;
      flow_rect wr = flow_node_rect_abs(f, n);
      flow_pt s = flow_to_screen(f, (flow_pt){ wr.x, wr.y });
      const flow_node_type *nt = flow_node_type_for(f, n->type);
      if (!nt || !nt->render) continue;
      flow_surface surf = { &cb, s.x, s.y, n->w, n->h };
      flow_render_ctx ctx = { f->view.zoom, n->flags, 0 };
      nt->render(n, &surf, ctx);
    }
  }

  /* handle markers: only on hovered/selected nodes (xyflow reveals on hover), plus
     the active connecting source so its marker stays visible mid-drag. ◉ on the border. */
  for (int i = 0; i < flow_node_count(f); i++) {
    flow_node *n = &flow_nodes(f)[i];
    if (!flow__node_handles_visible(f, n)) continue;   /* same gate as flow_hit_handle */
    int hc = flow_node_handle_count(f, n->id);
    for (int j = 0; j < hc; j++) {
      const flow_handle *h = flow_node_handle_at(f, n->id, j);
      flow_pt s = flow__handle_screen(f, n, h);         /* same projection as flow_hit_handle */
      unsigned bold = (n->id == f->conn_node && h &&
                       strncmp(h->id, f->conn_handle, sizeof h->id) == 0) ? FLOW_BOLD : 0;
      flow_cellbuf_put(&cb, s.x, s.y, 0x25C9, FLOW_FG, FLOW_BG, bold);  /* ◉ */
    }
  }

  /* in-flight connection preview: dashed rubber-band from the source handle to the
     free cursor cell. No arrowhead — overwrite the router's last cell with a dash. */
  if (f->conn_active) {
    flow_node *sn = flow_get_node(f, f->conn_node);
    const flow_handle *sh = sn ? flow__handle_named(f, f->conn_node, f->conn_handle) : NULL;
    if (sn) {
      flow_pos sp = sh ? sh->pos : FLOW_RIGHT;
      flow_pt sa = flow__anchor_outward(flow_handle_anchor(f, sn, sh), sp);
      flow_pt ss = flow_to_screen(f, sa);
      flow_route rt = {0};
      flow_route_orthogonal(ss, sp, f->conn_end, FLOW_LEFT, &rt);
      /* skip the LAST cell: the router stamps an arrowhead there — a preview has none. */
      int last = rt.count - 1;
      for (int c = 0; c < last; c++)
        if (((rt.cells[c].x + rt.cells[c].y) & 1) == 0)        /* dashed: every other cell */
          flow_cellbuf_put(&cb, rt.cells[c].x, rt.cells[c].y, rt.cells[c].ch, FLOW_FG, FLOW_BG, 0);
      free(rt.cells);
    }
  }

  /* marquee box (after nodes, before minimap/overlay so app panels still win).
     anchor/cur are SCREEN coords; stroke a normalized border with a distinct glyph. */
  if (f->marquee_on) {
    int x0 = f->marquee_anchor.x, x1 = f->marquee_cur.x;
    int y0 = f->marquee_anchor.y, y1 = f->marquee_cur.y;
    if (x1 < x0) { int t = x0; x0 = x1; x1 = t; }
    if (y1 < y0) { int t = y0; y0 = y1; y1 = t; }
    for (int x = x0; x <= x1; x++) {                       /* horizontal edges */
      flow_cellbuf_put(&cb, x, y0, 0x2592, FLOW_FG, FLOW_BG, 0);  /* ▒ */
      flow_cellbuf_put(&cb, x, y1, 0x2592, FLOW_FG, FLOW_BG, 0);
    }
    for (int y = y0; y <= y1; y++) {                       /* vertical edges */
      flow_cellbuf_put(&cb, x0, y, 0x2592, FLOW_FG, FLOW_BG, 0);
      flow_cellbuf_put(&cb, x1, y, 0x2592, FLOW_FG, FLOW_BG, 0);
    }
  }

  if (f->minimap.enabled) flow__minimap(f, &cb);
  if (f->cb.on_overlay) { flow_surface ov = { &cb, 0, 0, cols, rows }; f->cb.on_overlay(f, &ov, f->cb.user); }

  /* built-in status/help bar: drawn LAST (after the app overlay) on the bottom
     row only, so it never fights the app's overlay on other rows. */
  if (f->statusbar && rows > 0) {
    flow_surface s = { &cb, 0, rows - 1, cols, 1 };
    for (int x = 0; x < cols; x++) flow_put(&s, x, 0, ' ', FLOW_FG, FLOW_BG, FLOW_REVERSE);
    flow_text(&s, 0, 0, " n:add  x:del  f:fit  ?:help  q:quit ", FLOW_FG, FLOW_BG, FLOW_REVERSE);
  }
}
#endif
/* ===================== src/flow_input.h ===================== */
/* ===== mouse input: SGR-1006 parser + drag/pan interaction ===== */
enum { FLOW_MOD_SHIFT = 1u, FLOW_MOD_META = 2u, FLOW_MOD_CTRL = 4u };
typedef enum { FLOW_MOUSE_PRESS, FLOW_MOUSE_RELEASE, FLOW_MOUSE_MOTION, FLOW_MOUSE_WHEEL } flow_mouse_type;
typedef struct {
  flow_mouse_type type;
  int button;        /* press/release/motion: 0=left,1=mid,2=right; wheel: 0=up,1=down,2=left,3=right */
  int x, y;          /* 0-based cell coordinates */
  unsigned mods;     /* FLOW_MOD_SHIFT | FLOW_MOD_META | FLOW_MOD_CTRL */
} flow_mouse_event;

/* Parse one SGR-1006 mouse sequence at s (length n). Returns bytes consumed, or 0 if
   s is not a complete mouse sequence (caller should treat the bytes otherwise). */
int  flow_parse_mouse(const char *s, int n, flow_mouse_event *ev);
void flow_handle_mouse(flow_t *f, const flow_mouse_event *ev);

#ifdef FLOW_IMPLEMENTATION
int flow_parse_mouse(const char *s, int n, flow_mouse_event *ev) {
  if (n < 4 || s[0] != '\x1b' || s[1] != '[' || s[2] != '<') return 0;
  int B = 0, X = 0, Y = 0, field = 0;
  for (int i = 3; i < n; i++) {
    char c = s[i];
    if (c >= '0' && c <= '9') { int *t = field == 0 ? &B : field == 1 ? &X : &Y; *t = *t * 10 + (c - '0'); }
    else if (c == ';') { if (++field > 2) return 0; }
    else if (c == 'M' || c == 'm') {
      ev->mods = ((B&4)?FLOW_MOD_SHIFT:0) | ((B&8)?FLOW_MOD_META:0) | ((B&16)?FLOW_MOD_CTRL:0);
      ev->x = X - 1; ev->y = Y - 1; ev->button = B & 3;
      if (B & 64)       ev->type = FLOW_MOUSE_WHEEL;
      else if (c == 'm') ev->type = FLOW_MOUSE_RELEASE;
      else if (B & 32)   ev->type = FLOW_MOUSE_MOTION;
      else               ev->type = FLOW_MOUSE_PRESS;
      return i + 1;
    }
    else return 0;   /* unexpected byte: not a mouse sequence */
  }
  return 0;          /* incomplete */
}
/* resolve an in-flight connection at a screen cell: complete on a target handle/node
   (handle id when one is hit, else the node's default), else cancel. Shared by the
   connectOnClick press path and the drag-complete release path. */
static void flow__resolve_connection_at(flow_t *f, flow_pt scr) {
  int tnode = -1; int hidx = flow_hit_handle(f, scr, &tnode);
  if (tnode == -1) tnode = flow_hit_node(f, scr);
  if (tnode != -1 && tnode != f->conn_node) {
    const flow_handle *th = (hidx >= 0) ? flow_node_handle_at(f, tnode, hidx) : NULL;
    flow_end_connection(f, tnode, th ? th->id : NULL);
  } else {
    flow_cancel_connection(f);             /* dropped on empty pane or the source */
  }
}
void flow_handle_mouse(flow_t *f, const flow_mouse_event *ev) {
  if (ev->type == FLOW_MOUSE_WHEEL) {
    switch (ev->button) {
      case 0: flow_pan(f, 0,  1); break;   /* wheel up    */
      case 1: flow_pan(f, 0, -1); break;   /* wheel down  */
      case 2: flow_pan(f, 1,  0); break;   /* wheel left  */
      case 3: flow_pan(f, -1, 0); break;   /* wheel right */
    }
    return;
  }
  flow_pt scr = { ev->x, ev->y };
  if (ev->type == FLOW_MOUSE_PRESS) {
    if (ev->button == 2) {                       /* right-click: cancel any in-flight connection, else context */
      if (f->conn_active) { flow_cancel_connection(f); return; }
      int id = flow_hit_node(f, scr);
      if (id != -1 && f->cb.on_node_context) f->cb.on_node_context(f, id, scr, f->cb.user);
      return;
    }
    if (ev->button == 0) {                       /* arm a press; classify on move/release */
      /* connectOnClick resolve: a press while already connecting (armed by a prior
         click) completes on a target handle/node, else cancels. Never arms drag. */
      if (f->conn_active) { flow__resolve_connection_at(f, scr); return; }
      f->mouse_down = 1; f->moved = 0; f->down_pos = scr;
      /* HIT PRECEDENCE (trio invariant): handle -> node-body -> pane. A later edge
         package inserts an edge-endpoint test BETWEEN handle and node-body here.
         Handles only hit on hovered/selected/connecting nodes (flow_hit_handle). */
      int hnode = -1; int hidx = flow_hit_handle(f, scr, &hnode);
      if (hidx >= 0 && hnode != -1) {
        const flow_handle *h = flow_node_handle_at(f, hnode, hidx);
        if (h && flow_begin_connection(f, hnode, h->id) == 0) {
          /* grabbed a source handle: do NOT arm node-drag/select. conn_* is orthogonal.
             Clear mouse_down so the trailing release (after the connection resolves) is
             a no-op and never falls into clear_selection/on_pane_click. */
          f->mouse_down = 0; f->down_node = -1; f->drag_node = -1; f->dragging_pan = 0;
          f->down_modsel = 0; f->marquee_active = 0;
          return;
        }
      }
      /* edge-endpoint test (BETWEEN handle and node-body): if the press lands EXACTLY on
         an endpoint cell of the topmost edge under the cursor, arm a reconnect drag and
         skip node-drag/select. Endpoints sit one cell OUTSIDE the node so this never
         steals an ordinary node-body press (require exact cell, not just within tol). */
      int eedge = flow_hit_edge(f, scr, 1);
      if (eedge != -1) {
        flow_pt ss, ts;
        int oks = flow_edge_endpoint_screen(f, flow_get_edge(f, eedge), 0, &ss);
        int okt = flow_edge_endpoint_screen(f, flow_get_edge(f, eedge), 1, &ts);
        int which = -1;
        if (okt && ts.x == scr.x && ts.y == scr.y) which = 1;        /* target endpoint */
        else if (oks && ss.x == scr.x && ss.y == scr.y) which = 0;   /* source endpoint */
        if (which != -1) {
          f->reconnect_edge = eedge; f->reconnect_which = which;
          f->mouse_down = 1; f->down_node = -1; f->drag_node = -1; f->dragging_pan = 0;
          f->down_modsel = 0; f->marquee_active = 0;
          return;
        }
      }
      f->down_node = flow_hit_node(f, scr);
      f->drag_node = -1; f->dragging_pan = 0;
      f->down_modsel = 0; f->marquee_active = 0;
      unsigned mod = ev->mods & (FLOW_MOD_SHIFT | FLOW_MOD_CTRL);
      if (f->down_node != -1) {
        if (mod) {                               /* shift/ctrl-click a node: modify the set NOW */
          if (ev->mods & FLOW_MOD_CTRL) flow_toggle_node(f, f->down_node);  /* toggle */
          else                          flow_select_node(f, f->down_node, 1);/* shift: additive add */
          f->down_modsel = 1;                    /* suppress release replace + on_node_click; arm group drag */
        }
        /* no-mod node press: classify on move/release as before (no select on press) */
      } else if (ev->mods & FLOW_MOD_SHIFT) {    /* shift-drag empty pane: arm marquee (anchor = down_pos) */
        f->marquee_active = 1;
      }
    }
  } else if (ev->type == FLOW_MOUSE_MOTION) {
    if (f->conn_active) {                         /* drag-connect: track free end + reveal candidate */
      if (scr.x != f->down_pos.x || scr.y != f->down_pos.y) f->moved = 1;
      flow_update_connection(f, scr);
      return;
    }
    if (f->reconnect_edge != -1) {                /* reconnect drag: just track movement, no pan/drag */
      if (scr.x != f->down_pos.x || scr.y != f->down_pos.y) f->moved = 1;
      return;
    }
    if (!f->mouse_down) return;
    if (!f->moved && (scr.x != f->down_pos.x || scr.y != f->down_pos.y)) {
      f->moved = 1;                              /* threshold crossed: begin drag, marquee, or pan */
      if (f->marquee_active) {
        f->marquee_on = 1; f->marquee_anchor = f->down_pos;
      } else if (f->down_node != -1) {
        flow_node *nd = flow_get_node(f, f->down_node);
        flow_pt w = flow_to_world(f, f->down_pos), a = flow_node_abs(f, nd);
        f->drag_node = f->down_node; f->drag_grab.x = w.x - a.x; f->drag_grab.y = w.y - a.y;
        f->drag_last_world = flow_to_world(f, f->down_pos);   /* multi-drag delta anchor */
        if (!(nd->flags & FLOW_SELECTED))        /* unselected node: plain drag REPLACES selection */
          flow_select_node(f, f->down_node, 0);  /* selectNodesOnDrag; selected node keeps the set (group drag) */
      } else {
        f->dragging_pan = 1; f->last_mouse = f->down_pos;
      }
    }
    if (f->marquee_on) {                          /* live marquee: replace-select within the box */
      f->marquee_cur = scr;
      flow_pt wa = flow_to_world(f, f->marquee_anchor), wc = flow_to_world(f, scr);
      flow_rect wr = { wa.x < wc.x ? wa.x : wc.x, wa.y < wc.y ? wa.y : wc.y,
                       (wa.x < wc.x ? wc.x - wa.x : wa.x - wc.x),
                       (wa.y < wc.y ? wc.y - wa.y : wa.y - wc.y) };
      flow_select_in_rect(f, wr, f->marquee_mode, 0);
    } else if (f->drag_node != -1) {
      if (flow_selected_count(f) > 1) {           /* MULTI-DRAG: shift whole set by per-motion world delta */
        flow_pt w = flow_to_world(f, scr);
        int dx = w.x - f->drag_last_world.x, dy = w.y - f->drag_last_world.y;
        if (dx || dy) {
          for (int i = 0; i < f->nnodes; i++) if (f->nodes[i].flags & FLOW_SELECTED) {
            flow_pt p = f->nodes[i].pos; flow_move_node(f, f->nodes[i].id, (flow_pt){ p.x + dx, p.y + dy });
          }
          f->drag_last_world = w;
        }
      } else {                                    /* single node: grab-offset move (unchanged) */
        flow_pt w = flow_to_world(f, scr);
        flow_move_node(f, f->drag_node, (flow_pt){ w.x - f->drag_grab.x, w.y - f->drag_grab.y });
      }
    } else if (f->dragging_pan) {
      flow_pan(f, scr.x - f->last_mouse.x, scr.y - f->last_mouse.y);
      f->last_mouse = scr;
    }
  } else if (ev->type == FLOW_MOUSE_RELEASE) {
    if (f->conn_active) {
      if (f->moved) {                            /* drag-connect: complete on target, else cancel */
        flow__resolve_connection_at(f, scr);
        f->mouse_down = 0; f->moved = 0;
      }
      /* else: the click that BEGAN the connection — stay armed for connectOnClick */
      return;
    }
    if (f->reconnect_edge != -1) {               /* finish an endpoint-reconnect drag */
      if (f->moved) {                            /* dragged: repoint onto a valid node, else leave unchanged */
        int hit = flow_hit_node(f, scr);
        if (hit != -1) flow_reconnect_edge(f, f->reconnect_edge, hit, "", f->reconnect_which);
      } else {                                   /* click on the endpoint, no drag: select the edge */
        flow_select_edge(f, f->reconnect_edge, 0);
      }
      f->reconnect_edge = -1; f->mouse_down = 0; f->moved = 0; f->down_node = -1;
      f->drag_node = -1; f->dragging_pan = 0; f->down_modsel = 0;
      f->marquee_active = 0; f->marquee_on = 0;
      return;
    }
    if (f->mouse_down && !f->moved) {            /* a click, not a drag */
      if (f->down_modsel) {
        /* shift/ctrl-click already applied on press: do NOT replace, do NOT fire on_node_click */
      } else if (f->down_node != -1) {
        flow_select_node(f, f->down_node, 0);
        if (f->cb.on_node_click) f->cb.on_node_click(f, f->down_node, f->cb.user);
      } else {
        int eclick = flow_hit_edge(f, scr, 1);   /* edge-body click-select before clearing/pane-click */
        if (eclick != -1) {
          flow_select_edge(f, eclick, 0);
        } else {
          flow_clear_selection(f);
          if (f->cb.on_pane_click) f->cb.on_pane_click(f, flow_to_world(f, scr), f->cb.user);
        }
      }
    }
    /* marquee finalize: selection already applied during motion; just clear state.
       A marqueed drag sets moved==1, so on_pane_click was never fired. */
    f->mouse_down = 0; f->moved = 0; f->drag_node = -1; f->dragging_pan = 0; f->down_node = -1;
    f->down_modsel = 0; f->marquee_active = 0; f->marquee_on = 0;
  }
}
#endif
/* ===================== src/flow_term.h ===================== */
/* ===== terminal: raw mode, alt-screen, size (impl-only POSIX deps) ===== */
void flow_term_setup(void);
void flow_term_restore(void);
int  flow_term_size(int *cols, int *rows);

#ifdef FLOW_IMPLEMENTATION
#include <termios.h>
#include <unistd.h>
#include <sys/ioctl.h>
static struct termios flow__saved_tio;
void flow_term_setup(void) {
  struct termios raw; tcgetattr(STDIN_FILENO, &flow__saved_tio); raw = flow__saved_tio;
  raw.c_lflag &= ~(ECHO | ICANON);
  tcsetattr(STDIN_FILENO, TCSAFLUSH, &raw);
  /* alt-screen, clear, hide cursor; enable SGR mouse (click+drag+wheel) */
  printf("\x1b[?1049h\x1b[2J\x1b[?25l\x1b[?1000h\x1b[?1002h\x1b[?1006h"); fflush(stdout);
}
void flow_term_restore(void) {
  printf("\x1b[?1006l\x1b[?1002l\x1b[?1000l\x1b[0m\x1b[?25h\x1b[?1049l"); fflush(stdout);
  tcsetattr(STDIN_FILENO, TCSAFLUSH, &flow__saved_tio);
}
int flow_term_size(int *cols, int *rows) {
  struct winsize ws;
  if (ioctl(STDOUT_FILENO, TIOCGWINSZ, &ws) != 0 || ws.ws_col == 0) return -1;
  *cols = ws.ws_col; *rows = ws.ws_row; return 0;
}
#endif
/* ===================== src/flow_run.h ===================== */
/* ===== present (diff+flush), feed (arrow-key pan), run loop ===== */
void flow_present(flow_t *f);
void flow_feed(flow_t *f, const char *bytes, int n);
void flow_run(flow_t *f);

#ifdef FLOW_IMPLEMENTATION
void flow_present(flow_t *f) {
  flow_cell *back = (flow_cell*)calloc((size_t)f->cols * f->rows, sizeof(flow_cell));
  flow_render(f, back, f->cols, f->rows);
  char *esc = flow_diff_emit(f->front, back, f->cols, f->rows);
  fputs(esc, stdout); fflush(stdout); free(esc);
  memcpy(f->front, back, (size_t)f->cols * f->rows * sizeof(flow_cell));
  free(back);
}
void flow_feed(flow_t *f, const char *b, int n) {
  int i = 0;
  while (i < n) {
    if (b[i] == '\x1b' && i + 2 < n && b[i+1] == '[' && b[i+2] == '<') {
      flow_mouse_event ev; int used = flow_parse_mouse(b + i, n - i, &ev);
      if (used > 0) { flow_handle_mouse(f, &ev); i += used; continue; }
    }
    int dk = flow_dispatch_key(f, b + i, n - i);   /* registry/built-in keys (NOT bare arrows, NOT 'q') */
    if (dk > 0) { i += dk; continue; }
    if (b[i] == '\x1b' && i + 2 < n && b[i+1] == '[') {
      switch (b[i+2]) {                          /* arrow-key pan */
        case 'A': flow_pan(f, 0,  1); i += 3; continue;   /* up    */
        case 'B': flow_pan(f, 0, -1); i += 3; continue;   /* down  */
        case 'C': flow_pan(f, -1, 0); i += 3; continue;   /* right */
        case 'D': flow_pan(f,  1, 0); i += 3; continue;   /* left  */
        default: break;
      }
    }
    /* lone ESC (not the start of a CSI) cancels an in-flight connection. Real
       mouse/arrow/Delete sequences all have b[i+1]=='[' and are consumed above. */
    if (b[i] == '\x1b' && (i + 1 >= n || b[i+1] != '[')) { flow_cancel_connection(f); i++; continue; }
    i++;
  }
}
void flow_run(flow_t *f) {
  int cols, rows;
  if (flow_term_size(&cols, &rows) == 0) flow_resize(f, cols, rows);
  flow_term_setup(); f->running = 1;
  flow_present(f);
  char buf[64];
  while (f->running) {
    int n = (int)read(STDIN_FILENO, buf, sizeof buf);
    if (n <= 0) break;
    for (int i = 0; i < n; i++) if (buf[i] == 'q') f->running = 0;
    flow_feed(f, buf, n);
    flow_present(f);
  }
  flow_term_restore();
}
#endif
#endif /* FLOW_H */
