/* flow.h — GENERATED by tools/amalgamate.sh. Do not edit; edit src/ instead. */
#ifndef FLOW_H
#define FLOW_H
/* ===================== src/flow_head.h ===================== */
/* flow — a C-based xyflow (terminal node-graph editor library). MIT.
 * Single-header; generated from src/ by tools/amalgamate.sh — DO NOT edit flow.h directly.
 * Terminal escape/raw-mode technique adapted from tuibox (Cubified, MIT). */
#include <stdint.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
/* ===================== src/flow_geom.h ===================== */
/* (module: filled in by a later task) */
/* ===================== src/flow_cell.h ===================== */
/* (module: filled in by a later task) */
/* ===================== src/flow_model.h ===================== */
/* (module: filled in by a later task) */
/* ===================== src/flow_route.h ===================== */
/* (module: filled in by a later task) */
/* ===================== src/flow_types.h ===================== */
/* (module: filled in by a later task) */
/* ===================== src/flow_render.h ===================== */
/* (module: filled in by a later task) */
/* ===================== src/flow_term.h ===================== */
/* (module: filled in by a later task) */
/* ===================== src/flow_run.h ===================== */
/* (module: filled in by a later task) */
#endif /* FLOW_H */
