/* flow.h — GENERATED by tools/amalgamate.sh. Do not edit; edit src/ instead. */
#ifndef FLOW_H
#define FLOW_H
/* ===================== src/flow_head.h ===================== */
/* flow — a C-based xyflow (terminal node-graph editor library). MIT.
 * Single-header; generated from src/ by tools/amalgamate.sh — DO NOT edit flow.h directly.
 * Terminal escape/raw-mode technique adapted from tuibox (Cubified, MIT). */
#include <stdint.h>
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
/* ===================== src/flow_geom.h ===================== */
/* ===== geometry (pure, no I/O) ===== */
typedef struct { int x, y; } flow_pt;
typedef struct { int x, y, w, h; } flow_rect;
typedef enum { FLOW_TOP, FLOW_RIGHT, FLOW_BOTTOM, FLOW_LEFT } flow_pos;
typedef struct { float ox, oy, zoom; } flow_viewport;

flow_pt   flow_project(flow_viewport v, flow_pt world);
flow_pt   flow_unproject(flow_viewport v, flow_pt screen);
int       flow_rect_contains(flow_rect r, flow_pt p);
flow_rect flow_rect_union(flow_rect a, flow_rect b);

#ifdef FLOW_IMPLEMENTATION
flow_pt flow_project(flow_viewport v, flow_pt world) {
  flow_pt s;
  s.x = (int)lroundf(world.x * v.zoom + v.ox);
  s.y = (int)lroundf(world.y * v.zoom + v.oy);
  return s;
}
flow_pt flow_unproject(flow_viewport v, flow_pt screen) {
  float z = (v.zoom == 0.0f) ? 1.0f : v.zoom;
  flow_pt w;
  w.x = (int)lroundf((screen.x - v.ox) / z);
  w.y = (int)lroundf((screen.y - v.oy) / z);
  return w;
}
int flow_rect_contains(flow_rect r, flow_pt p) {
  return p.x >= r.x && p.x < r.x + r.w && p.y >= r.y && p.y < r.y + r.h;
}
flow_rect flow_rect_union(flow_rect a, flow_rect b) {
  int x0 = a.x < b.x ? a.x : b.x, y0 = a.y < b.y ? a.y : b.y;
  int ax1 = a.x + a.w, ay1 = a.y + a.h, bx1 = b.x + b.w, by1 = b.y + b.h;
  int x1 = ax1 > bx1 ? ax1 : bx1, y1 = ay1 > by1 ? ay1 : by1;
  flow_rect r = { x0, y0, x1 - x0, y1 - y0 };
  return r;
}
#endif
/* ===================== src/flow_cell.h ===================== */
/* ===== cells, surface, box, utf8, damage diff ===== */
enum { FLOW_BOLD = 1u, FLOW_REVERSE = 2u, FLOW_DIM = 4u, FLOW_UNDERLINE = 8u };
#define FLOW_FG 7
#define FLOW_BG 0
typedef struct { uint32_t ch; uint8_t fg, bg, attr; } flow_cell;

typedef struct { flow_cell *cells; int w, h; } flow_cellbuf;
struct flow_surface { flow_cellbuf *cb; int ox, oy, w, h; };
typedef struct flow_surface flow_surface;

/* route output type — declared here so the edge vtable can reference it; impl in flow_route.h */
typedef struct { uint32_t ch; int x, y; } flow_route_cell;
typedef struct { flow_route_cell *cells; int count, cap; flow_pt label_anchor; } flow_route;

int  flow_utf8(uint32_t cp, char out[5]);
int  flow_utf8_decode(const char *s, uint32_t *cp);
void flow_cellbuf_clear(flow_cellbuf *cb, uint8_t fg, uint8_t bg);
void flow_cellbuf_put(flow_cellbuf *cb, int x, int y, uint32_t ch, uint8_t fg, uint8_t bg, uint8_t attr);
void flow_put(flow_surface *s, int x, int y, uint32_t ch, uint8_t fg, uint8_t bg, uint8_t attr);
void flow_text(flow_surface *s, int x, int y, const char *utf8, uint8_t fg, uint8_t bg, uint8_t attr);
void flow_box(flow_surface *s, int x, int y, int w, int h, uint8_t fg, uint8_t bg, unsigned style);
int  flow_surface_w(const flow_surface *s);
int  flow_surface_h(const flow_surface *s);
char *flow_diff_emit(const flow_cell *front, const flow_cell *back, int cols, int rows);

#ifdef FLOW_IMPLEMENTATION
int flow_utf8(uint32_t cp, char out[5]) {
  if (cp < 0x80) { out[0] = (char)cp; out[1] = 0; return 1; }
  if (cp < 0x800) { out[0] = (char)(0xC0 | (cp >> 6)); out[1] = (char)(0x80 | (cp & 0x3F)); out[2] = 0; return 2; }
  if (cp < 0x10000) { out[0] = (char)(0xE0 | (cp >> 12)); out[1] = (char)(0x80 | ((cp >> 6) & 0x3F));
    out[2] = (char)(0x80 | (cp & 0x3F)); out[3] = 0; return 3; }
  out[0] = (char)(0xF0 | (cp >> 18)); out[1] = (char)(0x80 | ((cp >> 12) & 0x3F));
  out[2] = (char)(0x80 | ((cp >> 6) & 0x3F)); out[3] = (char)(0x80 | (cp & 0x3F)); out[4] = 0; return 4;
}
int flow_utf8_decode(const char *s, uint32_t *cp) {
  const unsigned char *u = (const unsigned char*)s;
  /* Each continuation check short-circuits before the next byte is read, so a
     truncated trailing sequence stops at the NUL instead of over-reading. */
  if (u[0] < 0x80) { *cp = u[0]; return 1; }
  if ((u[0] & 0xE0) == 0xC0) {
    if ((u[1] & 0xC0) != 0x80) { *cp = u[0]; return 1; }
    *cp = ((uint32_t)(u[0]&0x1F)<<6)|(u[1]&0x3F); return 2;
  }
  if ((u[0] & 0xF0) == 0xE0) {
    if ((u[1] & 0xC0) != 0x80 || (u[2] & 0xC0) != 0x80) { *cp = u[0]; return 1; }
    *cp = ((uint32_t)(u[0]&0x0F)<<12)|((uint32_t)(u[1]&0x3F)<<6)|(u[2]&0x3F); return 3;
  }
  if ((u[0] & 0xF8) == 0xF0) {
    if ((u[1]&0xC0)!=0x80 || (u[2]&0xC0)!=0x80 || (u[3]&0xC0)!=0x80) { *cp = u[0]; return 1; }
    *cp = ((uint32_t)(u[0]&0x07)<<18)|((uint32_t)(u[1]&0x3F)<<12)|((uint32_t)(u[2]&0x3F)<<6)|(u[3]&0x3F); return 4;
  }
  *cp = u[0]; return 1;   /* invalid lead byte */
}
void flow_cellbuf_clear(flow_cellbuf *cb, uint8_t fg, uint8_t bg) {
  for (int i = 0; i < cb->w * cb->h; i++) { cb->cells[i].ch = ' '; cb->cells[i].fg = fg; cb->cells[i].bg = bg; cb->cells[i].attr = 0; }
}
void flow_cellbuf_put(flow_cellbuf *cb, int x, int y, uint32_t ch, uint8_t fg, uint8_t bg, uint8_t attr) {
  if (x < 0 || y < 0 || x >= cb->w || y >= cb->h) return;
  flow_cell *c = &cb->cells[y * cb->w + x]; c->ch = ch; c->fg = fg; c->bg = bg; c->attr = attr;
}
void flow_put(flow_surface *s, int x, int y, uint32_t ch, uint8_t fg, uint8_t bg, uint8_t attr) {
  if (x < 0 || y < 0 || x >= s->w || y >= s->h) return;            /* logical clip to node box */
  flow_cellbuf_put(s->cb, s->ox + x, s->oy + y, ch, fg, bg, attr); /* physical clip to buffer  */
}
void flow_text(flow_surface *s, int x, int y, const char *u, uint8_t fg, uint8_t bg, uint8_t attr) {
  int i = 0; while (*u) { uint32_t cp; int n = flow_utf8_decode(u, &cp); u += n; flow_put(s, x + i, y, cp, fg, bg, attr); i++; }
}
void flow_box(flow_surface *s, int x, int y, int w, int h, uint8_t fg, uint8_t bg, unsigned style) {
  uint8_t a = (style & FLOW_BOLD) ? FLOW_BOLD : 0;
  if (w < 2 || h < 2) return;
  flow_put(s, x, y, 0x250C, fg, bg, a);
  flow_put(s, x+w-1, y, 0x2510, fg, bg, a);
  flow_put(s, x, y+h-1, 0x2514, fg, bg, a);
  flow_put(s, x+w-1, y+h-1, 0x2518, fg, bg, a);
  for (int i = 1; i < w-1; i++) { flow_put(s, x+i, y, 0x2500, fg, bg, a); flow_put(s, x+i, y+h-1, 0x2500, fg, bg, a); }
  for (int j = 1; j < h-1; j++) { flow_put(s, x, y+j, 0x2502, fg, bg, a); flow_put(s, x+w-1, y+j, 0x2502, fg, bg, a); }
}
int flow_surface_w(const flow_surface *s) { return s->w; }
int flow_surface_h(const flow_surface *s) { return s->h; }

static void flow__sb(char **out, size_t *cap, size_t *len, const char *s, int n) {
  if (*len + (size_t)n + 1 > *cap) { while (*len + (size_t)n + 1 > *cap) *cap *= 2; *out = (char*)realloc(*out, *cap); }
  memcpy(*out + *len, s, n); *len += n; (*out)[*len] = 0;
}
char *flow_diff_emit(const flow_cell *front, const flow_cell *back, int cols, int rows) {
  size_t cap = 64, len = 0; char *out = (char*)malloc(cap); out[0] = 0;
  int cury = -1, curx = -1, have_style = 0; uint8_t lfg = 0, lbg = 0, lattr = 0;
  char tmp[64], u[5];
  for (int y = 0; y < rows; y++) for (int x = 0; x < cols; x++) {
    int i = y * cols + x; flow_cell b = back[i], f = front[i];
    if (b.ch == f.ch && b.fg == f.fg && b.bg == f.bg && b.attr == f.attr) continue;
    if (y != cury || x != curx) { int n = snprintf(tmp, sizeof tmp, "\x1b[%d;%dH", y+1, x+1); flow__sb(&out,&cap,&len,tmp,n); }
    if (!have_style || b.fg != lfg || b.bg != lbg || b.attr != lattr) {
      int k = 0; k += snprintf(tmp+k, sizeof tmp-k, "\x1b[0");
      if (b.attr & FLOW_BOLD) k += snprintf(tmp+k, sizeof tmp-k, ";1");
      if (b.attr & FLOW_REVERSE) k += snprintf(tmp+k, sizeof tmp-k, ";7");
      k += snprintf(tmp+k, sizeof tmp-k, ";38;5;%u;48;5;%um", b.fg, b.bg);
      flow__sb(&out,&cap,&len,tmp,k); lfg=b.fg; lbg=b.bg; lattr=b.attr; have_style=1;
    }
    uint32_t ch = b.ch ? b.ch : ' '; int n = flow_utf8(ch, u); flow__sb(&out,&cap,&len,u,n);
    curx = x + 1; cury = y;
  }
  return out;
}
#endif
/* ===================== src/flow_model.h ===================== */
/* ===== model: engine, nodes, edges, vtable types, transform, bounds, hit-test ===== */
enum { FLOW_SELECTED = 1u, FLOW_DRAGGING = 2u, FLOW_HOVERED = 4u };
typedef enum { FLOW_HANDLE_SOURCE, FLOW_HANDLE_TARGET, FLOW_HANDLE_BOTH } flow_handle_kind;
typedef struct { char id[16]; flow_handle_kind kind; flow_pos pos; int along; } flow_handle;

typedef struct { int id; char type[32]; flow_pt pos; int parent; int w, h; void *data; unsigned flags; } flow_node;
typedef struct { int id, source, target; char source_handle[16], target_handle[16];
                 char type[16]; char *label; void *data; unsigned flags; } flow_edge;

typedef struct { float zoom; unsigned flags; int lod; } flow_render_ctx;
typedef struct { const char *type;
  void (*measure)(const flow_node*, int*, int*);
  void (*render)(const flow_node*, flow_surface*, flow_render_ctx);
  const flow_handle *handles; int handle_count; } flow_node_type;
typedef struct { const char *type;
  void (*route)(flow_pt s, flow_pos sp, flow_pt t, flow_pos tp, flow_route *out); } flow_edge_type;

typedef struct flow flow_t;

flow_t *flow_new(int cols, int rows);
void    flow_free(flow_t *f);
void    flow_resize(flow_t *f, int cols, int rows);
void    flow_register_node_type(flow_t *f, const flow_node_type *t);
void    flow_register_edge_type(flow_t *f, const flow_edge_type *t);
const flow_node_type *flow_node_type_for(flow_t *f, const char *type);
const flow_edge_type *flow_edge_type_for(flow_t *f, const char *type);
void    flow_measure_node(flow_t *f, flow_node *n);
int     flow_add_node(flow_t *f, const char *type, flow_pt pos, void *data);
int     flow_add_edge(flow_t *f, int src, int dst, const char *sh, const char *th);
flow_node *flow_get_node(flow_t *f, int id);
flow_edge *flow_get_edge(flow_t *f, int id);
int     flow_node_count(flow_t *f);
int     flow_edge_count(flow_t *f);
flow_node *flow_nodes(flow_t *f);
flow_edge *flow_edges(flow_t *f);
flow_pt   flow_node_abs(flow_t *f, const flow_node *n);
flow_rect flow_node_rect_abs(flow_t *f, const flow_node *n);
flow_rect flow_bounds(flow_t *f);
int       flow_hit_node(flow_t *f, flow_pt screen);
void      flow_pan(flow_t *f, int dx, int dy);
flow_pt   flow_to_screen(flow_t *f, flow_pt world_abs);
flow_pt   flow_to_world(flow_t *f, flow_pt screen);
flow_viewport flow_view_get(flow_t *f);

#ifdef FLOW_IMPLEMENTATION
struct flow {
  flow_node *nodes; int nnodes, capnodes, nextid;
  flow_edge *edges; int nedges, capedges, nexteid;
  const flow_node_type **ntypes; int nntypes;
  const flow_edge_type **etypes; int netypes;
  flow_viewport view; int cols, rows; flow_cell *front; int running;
};
static void *flow__grow(void *arr, int *cap, int need, size_t sz) {
  if (need <= *cap) return arr;
  int c = *cap ? *cap : 8; while (c < need) c *= 2;
  arr = realloc(arr, (size_t)c * sz); *cap = c; return arr;
}
flow_t *flow_new(int cols, int rows) {
  flow_t *f = (flow_t*)calloc(1, sizeof *f);
  f->view.zoom = 1; f->cols = cols; f->rows = rows; f->nextid = 1; f->nexteid = 1;
  f->front = (flow_cell*)calloc((size_t)cols * rows, sizeof(flow_cell));
  return f;
}
void flow_free(flow_t *f) {
  if (!f) return;
  for (int i = 0; i < f->nedges; i++) free(f->edges[i].label);
  free(f->nodes); free(f->edges); free(f->ntypes); free(f->etypes); free(f->front); free(f);
}
void flow_resize(flow_t *f, int cols, int rows) {
  f->cols = cols; f->rows = rows; free(f->front);
  f->front = (flow_cell*)calloc((size_t)cols * rows, sizeof(flow_cell));
}
void flow_register_node_type(flow_t *f, const flow_node_type *t) {
  f->ntypes = (const flow_node_type**)realloc(f->ntypes, (f->nntypes + 1) * sizeof *f->ntypes);
  f->ntypes[f->nntypes++] = t;
}
void flow_register_edge_type(flow_t *f, const flow_edge_type *t) {
  f->etypes = (const flow_edge_type**)realloc(f->etypes, (f->netypes + 1) * sizeof *f->etypes);
  f->etypes[f->netypes++] = t;
}
const flow_node_type *flow_node_type_for(flow_t *f, const char *type) {
  for (int i = 0; i < f->nntypes; i++) if (strcmp(f->ntypes[i]->type, type) == 0) return f->ntypes[i];
  return NULL;
}
const flow_edge_type *flow_edge_type_for(flow_t *f, const char *type) {
  for (int i = 0; i < f->netypes; i++) if (strcmp(f->etypes[i]->type, type) == 0) return f->etypes[i];
  return NULL;
}
void flow_measure_node(flow_t *f, flow_node *n) {
  const flow_node_type *t = flow_node_type_for(f, n->type);
  if (t && t->measure) { int w = 0, h = 0; t->measure(n, &w, &h); n->w = w; n->h = h; }
  else { n->w = 4; n->h = 3; }
}
int flow_add_node(flow_t *f, const char *type, flow_pt pos, void *data) {
  f->nodes = (flow_node*)flow__grow(f->nodes, &f->capnodes, f->nnodes + 1, sizeof(flow_node));
  flow_node *n = &f->nodes[f->nnodes++]; memset(n, 0, sizeof *n);
  n->id = f->nextid++; snprintf(n->type, sizeof n->type, "%s", type ? type : "default");
  n->pos = pos; n->parent = -1; n->data = data; flow_measure_node(f, n);
  return n->id;
}
int flow_add_edge(flow_t *f, int src, int dst, const char *sh, const char *th) {
  if (src == dst) return -1;
  if (!flow_get_node(f, src) || !flow_get_node(f, dst)) return -1;
  for (int i = 0; i < f->nedges; i++) if (f->edges[i].source == src && f->edges[i].target == dst) return -1;
  f->edges = (flow_edge*)flow__grow(f->edges, &f->capedges, f->nedges + 1, sizeof(flow_edge));
  flow_edge *e = &f->edges[f->nedges++]; memset(e, 0, sizeof *e);
  e->id = f->nexteid++; e->source = src; e->target = dst;
  snprintf(e->source_handle, sizeof e->source_handle, "%s", sh ? sh : "");
  snprintf(e->target_handle, sizeof e->target_handle, "%s", th ? th : "");
  return e->id;
}
flow_node *flow_get_node(flow_t *f, int id) { for (int i = 0; i < f->nnodes; i++) if (f->nodes[i].id == id) return &f->nodes[i]; return NULL; }
flow_edge *flow_get_edge(flow_t *f, int id) { for (int i = 0; i < f->nedges; i++) if (f->edges[i].id == id) return &f->edges[i]; return NULL; }
int flow_node_count(flow_t *f) { return f->nnodes; }
int flow_edge_count(flow_t *f) { return f->nedges; }
flow_node *flow_nodes(flow_t *f) { return f->nodes; }
flow_edge *flow_edges(flow_t *f) { return f->edges; }
flow_pt flow_node_abs(flow_t *f, const flow_node *n) {
  flow_pt p = n->pos; int parent = n->parent, guard = 0;
  while (parent != -1 && guard++ < 1024) { flow_node *pn = flow_get_node(f, parent); if (!pn) break;
    p.x += pn->pos.x; p.y += pn->pos.y; parent = pn->parent; }
  return p;
}
flow_rect flow_node_rect_abs(flow_t *f, const flow_node *n) { flow_pt a = flow_node_abs(f, n); flow_rect r = { a.x, a.y, n->w, n->h }; return r; }
flow_rect flow_bounds(flow_t *f) {
  if (f->nnodes == 0) { flow_rect z = {0,0,0,0}; return z; }
  flow_rect b = flow_node_rect_abs(f, &f->nodes[0]);
  for (int i = 1; i < f->nnodes; i++) b = flow_rect_union(b, flow_node_rect_abs(f, &f->nodes[i]));
  return b;
}
int flow_hit_node(flow_t *f, flow_pt screen) {
  for (int i = f->nnodes - 1; i >= 0; i--) {        /* topmost first */
    flow_node *n = &f->nodes[i]; flow_rect wr = flow_node_rect_abs(f, n);
    flow_pt s = flow_to_screen(f, (flow_pt){ wr.x, wr.y });
    flow_rect sr = { s.x, s.y, wr.w, wr.h };          /* zoom==1 in increment 1: size unscaled */
    if (flow_rect_contains(sr, screen)) return n->id;
  }
  return -1;
}
void flow_pan(flow_t *f, int dx, int dy) { f->view.ox += dx; f->view.oy += dy; }
flow_pt flow_to_screen(flow_t *f, flow_pt world_abs) { return flow_project(f->view, world_abs); }
flow_pt flow_to_world(flow_t *f, flow_pt screen) { return flow_unproject(f->view, screen); }
flow_viewport flow_view_get(flow_t *f) { return f->view; }
#endif
/* ===================== src/flow_route.h ===================== */
/* ===== edge routing: orthogonal step router via path-connectivity glyphs ===== */
void flow_route_push(flow_route *r, int x, int y, uint32_t ch);
void flow_route_orthogonal(flow_pt s, flow_pos sp, flow_pt t, flow_pos tp, flow_route *out);
extern const flow_edge_type flow_default_edge_type;

#ifdef FLOW_IMPLEMENTATION
const flow_edge_type flow_default_edge_type = { "default", flow_route_orthogonal };

void flow_route_push(flow_route *r, int x, int y, uint32_t ch) {
  if (r->count >= r->cap) { r->cap = r->cap ? r->cap * 2 : 16; r->cells = (flow_route_cell*)realloc(r->cells, r->cap * sizeof *r->cells); }
  r->cells[r->count].x = x; r->cells[r->count].y = y; r->cells[r->count].ch = ch; r->count++;
}
static void flow__addpt(flow_pt **a, int *n, int *cap, int x, int y) {
  if (*n > 0 && (*a)[*n-1].x == x && (*a)[*n-1].y == y) return;
  if (*n >= *cap) { *cap = *cap ? *cap * 2 : 32; *a = (flow_pt*)realloc(*a, *cap * sizeof(flow_pt)); }
  (*a)[*n].x = x; (*a)[*n].y = y; (*n)++;
}
/* direction bit from delta (neighbor relative to cell): N=1 S=2 E=4 W=8 */
static unsigned flow__dir(int dx, int dy) { unsigned m = 0; if (dy < 0) m|=1; if (dy > 0) m|=2; if (dx > 0) m|=4; if (dx < 0) m|=8; return m; }
static uint32_t flow__glyph(unsigned m) {
  switch (m) {
    case 4: case 8: case 12: return 0x2500;   /* - (E,W,EW) */
    case 1: case 2: case 3:  return 0x2502;   /* | (N,S,NS) */
    case 6:  return 0x250C;  /* E|S */
    case 10: return 0x2510;  /* W|S */
    case 5:  return 0x2514;  /* E|N */
    case 9:  return 0x2518;  /* W|N */
    default: return 0x2500;
  }
}
void flow_route_orthogonal(flow_pt s, flow_pos sp, flow_pt t, flow_pos tp, flow_route *out) {
  (void)sp; (void)tp;
  flow_pt *p = NULL; int n = 0, cap = 0;
  int dx = t.x - s.x, dy = t.y - s.y, adx = dx<0?-dx:dx, ady = dy<0?-dy:dy;
  int sx = dx >= 0 ? 1 : -1, sy = dy >= 0 ? 1 : -1;
  if (adx >= ady) {                 /* H-V-H, bend at mid column */
    int mx = (s.x + t.x) / 2;
    for (int x = s.x; ; x += sx) { flow__addpt(&p,&n,&cap,x,s.y); if (x == mx) break; }
    for (int y = s.y; ; y += sy) { flow__addpt(&p,&n,&cap,mx,y); if (y == t.y) break; }
    for (int x = mx; ; x += sx) { flow__addpt(&p,&n,&cap,x,t.y); if (x == t.x) break; }
  } else {                          /* V-H-V, bend at mid row */
    int my = (s.y + t.y) / 2;
    for (int y = s.y; ; y += sy) { flow__addpt(&p,&n,&cap,s.x,y); if (y == my) break; }
    for (int x = s.x; ; x += sx) { flow__addpt(&p,&n,&cap,x,my); if (x == t.x) break; }
    for (int y = my; ; y += sy) { flow__addpt(&p,&n,&cap,t.x,y); if (y == t.y) break; }
  }
  for (int i = 0; i < n; i++) {
    unsigned m = 0;
    if (i > 0)     m |= flow__dir(p[i-1].x - p[i].x, p[i-1].y - p[i].y);
    if (i < n - 1) m |= flow__dir(p[i+1].x - p[i].x, p[i+1].y - p[i].y);
    flow_route_push(out, p[i].x, p[i].y, flow__glyph(m));
  }
  if (n > 0) {                      /* arrowhead at the target end, pointing along the approach */
    int ax, ay;
    if (n >= 2) { ax = p[n-1].x - p[n-2].x; ay = p[n-1].y - p[n-2].y; }
    else        { ax = t.x - s.x;           ay = t.y - s.y; }
    uint32_t arrow = ax > 0 ? 0x25B6 : ax < 0 ? 0x25C0 : ay > 0 ? 0x25BC : 0x25B2;
    out->cells[out->count - 1].ch = arrow;
    out->label_anchor = p[n/2];
  }
  free(p);
}
#endif
/* ===================== src/flow_types.h ===================== */
/* ===== default node type (data = C-string label) + register-defaults ===== */
extern const flow_node_type flow_default_node_type;
void flow_register_defaults(flow_t *f);

#ifdef FLOW_IMPLEMENTATION
static void flow__default_measure(const flow_node *n, int *w, int *h) {
  const char *label = n->data ? (const char*)n->data : "";
  int len = (int)strlen(label); if (len < 1) len = 1;
  *w = len + 4; *h = 3;
}
static void flow__default_render(const flow_node *n, flow_surface *s, flow_render_ctx ctx) {
  const char *label = n->data ? (const char*)n->data : "";
  unsigned bold = (ctx.flags & FLOW_SELECTED) ? FLOW_BOLD : 0;
  flow_box(s, 0, 0, flow_surface_w(s), flow_surface_h(s), FLOW_FG, FLOW_BG, bold);
  flow_text(s, 2, 1, label, FLOW_FG, FLOW_BG, bold);
}
const flow_node_type flow_default_node_type = { "default", flow__default_measure, flow__default_render, NULL, 0 };
void flow_register_defaults(flow_t *f) {
  flow_register_node_type(f, &flow_default_node_type);
  flow_register_edge_type(f, &flow_default_edge_type);
}
#endif
/* ===================== src/flow_render.h ===================== */
/* ===== compose: render edges + nodes into a cell buffer ===== */
void flow_render(flow_t *f, flow_cell *out, int cols, int rows);

#ifdef FLOW_IMPLEMENTATION
void flow_render(flow_t *f, flow_cell *out, int cols, int rows) {
  flow_cellbuf cb = { out, cols, rows };
  flow_cellbuf_clear(&cb, FLOW_FG, FLOW_BG);

  /* edges first (drawn under nodes) */
  for (int i = 0; i < flow_edge_count(f); i++) {
    flow_edge *e = &flow_edges(f)[i];
    flow_node *sn = flow_get_node(f, e->source), *tn = flow_get_node(f, e->target);
    if (!sn || !tn) continue;
    flow_rect sr = flow_node_rect_abs(f, sn), tr = flow_node_rect_abs(f, tn);
    flow_pt sa = { sr.x + sr.w, sr.y + sr.h / 2 };   /* one cell right of source border */
    flow_pt ta = { tr.x - 1,    tr.y + tr.h / 2 };   /* one cell left of target border  */
    flow_pt ss = flow_to_screen(f, sa), ts = flow_to_screen(f, ta);
    const flow_edge_type *et = flow_edge_type_for(f, e->type[0] ? e->type : "default");
    if (!et) et = &flow_default_edge_type;
    flow_route rt = {0};
    et->route(ss, FLOW_RIGHT, ts, FLOW_LEFT, &rt);
    for (int c = 0; c < rt.count; c++)
      flow_cellbuf_put(&cb, rt.cells[c].x, rt.cells[c].y, rt.cells[c].ch, FLOW_FG, FLOW_BG, 0);
    free(rt.cells);
  }

  /* nodes on top, in insertion order (selected-last refinement comes in a later increment) */
  for (int i = 0; i < flow_node_count(f); i++) {
    flow_node *n = &flow_nodes(f)[i];
    flow_rect wr = flow_node_rect_abs(f, n);
    flow_pt s = flow_to_screen(f, (flow_pt){ wr.x, wr.y });
    const flow_node_type *nt = flow_node_type_for(f, n->type);
    if (!nt || !nt->render) continue;
    flow_surface surf = { &cb, s.x, s.y, n->w, n->h };
    flow_render_ctx ctx = { f->view.zoom, n->flags, 0 };
    nt->render(n, &surf, ctx);
  }
}
#endif
/* ===================== src/flow_term.h ===================== */
/* ===== terminal: raw mode, alt-screen, size (impl-only POSIX deps) ===== */
void flow_term_setup(void);
void flow_term_restore(void);
int  flow_term_size(int *cols, int *rows);

#ifdef FLOW_IMPLEMENTATION
#include <termios.h>
#include <unistd.h>
#include <sys/ioctl.h>
static struct termios flow__saved_tio;
void flow_term_setup(void) {
  struct termios raw; tcgetattr(STDIN_FILENO, &flow__saved_tio); raw = flow__saved_tio;
  raw.c_lflag &= ~(ECHO | ICANON);
  tcsetattr(STDIN_FILENO, TCSAFLUSH, &raw);
  printf("\x1b[?1049h\x1b[2J\x1b[?25l"); fflush(stdout);   /* alt-screen, clear, hide cursor */
}
void flow_term_restore(void) {
  printf("\x1b[0m\x1b[?25h\x1b[?1049l"); fflush(stdout);
  tcsetattr(STDIN_FILENO, TCSAFLUSH, &flow__saved_tio);
}
int flow_term_size(int *cols, int *rows) {
  struct winsize ws;
  if (ioctl(STDOUT_FILENO, TIOCGWINSZ, &ws) != 0 || ws.ws_col == 0) return -1;
  *cols = ws.ws_col; *rows = ws.ws_row; return 0;
}
#endif
/* ===================== src/flow_run.h ===================== */
/* ===== present (diff+flush), feed (arrow-key pan), run loop ===== */
void flow_present(flow_t *f);
void flow_feed(flow_t *f, const char *bytes, int n);
void flow_run(flow_t *f);

#ifdef FLOW_IMPLEMENTATION
void flow_present(flow_t *f) {
  flow_cell *back = (flow_cell*)calloc((size_t)f->cols * f->rows, sizeof(flow_cell));
  flow_render(f, back, f->cols, f->rows);
  char *esc = flow_diff_emit(f->front, back, f->cols, f->rows);
  fputs(esc, stdout); fflush(stdout); free(esc);
  memcpy(f->front, back, (size_t)f->cols * f->rows * sizeof(flow_cell));
  free(back);
}
void flow_feed(flow_t *f, const char *b, int n) {
  for (int i = 0; i + 2 < n; i++) {
    if (b[i] == '\x1b' && b[i+1] == '[') {
      switch (b[i+2]) {
        case 'A': flow_pan(f, 0,  1); break;   /* up    */
        case 'B': flow_pan(f, 0, -1); break;   /* down  */
        case 'C': flow_pan(f, -1, 0); break;   /* right */
        case 'D': flow_pan(f,  1, 0); break;   /* left  */
        default: break;
      }
    }
  }
}
void flow_run(flow_t *f) {
  int cols, rows;
  if (flow_term_size(&cols, &rows) == 0) flow_resize(f, cols, rows);
  flow_term_setup(); f->running = 1;
  flow_present(f);
  char buf[64];
  while (f->running) {
    int n = (int)read(STDIN_FILENO, buf, sizeof buf);
    if (n <= 0) break;
    for (int i = 0; i < n; i++) if (buf[i] == 'q') f->running = 0;
    flow_feed(f, buf, n);
    flow_present(f);
  }
  flow_term_restore();
}
#endif
#endif /* FLOW_H */
