#!/bin/sh
# Concatenate src/ fragments into the single-header flow.h
set -e
out=flow.h
modules="flow_head flow_geom flow_cell flow_model flow_view flow_route flow_types flow_render flow_json flow_input flow_term flow_run"
{
  echo '/* flow.h — GENERATED by tools/amalgamate.sh. Do not edit; edit src/ instead. */'
  echo '#ifndef FLOW_H'
  echo '#define FLOW_H'
  for m in $modules; do
    echo "/* ===================== src/$m.h ===================== */"
    cat "src/$m.h"
  done
  echo '#endif /* FLOW_H */'
} > "$out"
echo "wrote $out"
